// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example.proto

/*
Package example is a generated protocol buffer package.

It is generated from these files:
	example.proto

It has these top-level messages:
	ExampleDocument
	LongDocument
	SaltedLongDocument
	SaltedExampleDocument
*/
package example

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ExampleDocument struct {
	ValueA      string `protobuf:"bytes,1,opt,name=ValueA" json:"ValueA,omitempty"`
	ValueB      string `protobuf:"bytes,2,opt,name=ValueB" json:"ValueB,omitempty"`
	Value1      int64  `protobuf:"varint,3,opt,name=Value1" json:"Value1,omitempty"`
	Value2      int64  `protobuf:"varint,4,opt,name=Value2" json:"Value2,omitempty"`
	ValueBytes1 []byte `protobuf:"bytes,5,opt,name=ValueBytes1,proto3" json:"ValueBytes1,omitempty"`
}

func (m *ExampleDocument) Reset()                    { *m = ExampleDocument{} }
func (m *ExampleDocument) String() string            { return proto.CompactTextString(m) }
func (*ExampleDocument) ProtoMessage()               {}
func (*ExampleDocument) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ExampleDocument) GetValueA() string {
	if m != nil {
		return m.ValueA
	}
	return ""
}

func (m *ExampleDocument) GetValueB() string {
	if m != nil {
		return m.ValueB
	}
	return ""
}

func (m *ExampleDocument) GetValue1() int64 {
	if m != nil {
		return m.Value1
	}
	return 0
}

func (m *ExampleDocument) GetValue2() int64 {
	if m != nil {
		return m.Value2
	}
	return 0
}

func (m *ExampleDocument) GetValueBytes1() []byte {
	if m != nil {
		return m.ValueBytes1
	}
	return nil
}

type LongDocument struct {
	Value0 int64 `protobuf:"varint,16,opt,name=Value0" json:"Value0,omitempty"`
	Value1 int64 `protobuf:"varint,1,opt,name=Value1" json:"Value1,omitempty"`
	Value2 int64 `protobuf:"varint,2,opt,name=Value2" json:"Value2,omitempty"`
	Value3 int64 `protobuf:"varint,3,opt,name=Value3" json:"Value3,omitempty"`
	Value4 int64 `protobuf:"varint,4,opt,name=Value4" json:"Value4,omitempty"`
	Value5 int64 `protobuf:"varint,5,opt,name=Value5" json:"Value5,omitempty"`
	Value6 int64 `protobuf:"varint,6,opt,name=Value6" json:"Value6,omitempty"`
	Value7 int64 `protobuf:"varint,7,opt,name=Value7" json:"Value7,omitempty"`
	Value8 int64 `protobuf:"varint,8,opt,name=Value8" json:"Value8,omitempty"`
	Value9 int64 `protobuf:"varint,9,opt,name=Value9" json:"Value9,omitempty"`
	ValueA int64 `protobuf:"varint,10,opt,name=ValueA" json:"ValueA,omitempty"`
	ValueB int64 `protobuf:"varint,11,opt,name=ValueB" json:"ValueB,omitempty"`
	ValueC int64 `protobuf:"varint,12,opt,name=ValueC" json:"ValueC,omitempty"`
	ValueD int64 `protobuf:"varint,13,opt,name=ValueD" json:"ValueD,omitempty"`
	ValueE int64 `protobuf:"varint,14,opt,name=ValueE" json:"ValueE,omitempty"`
}

func (m *LongDocument) Reset()                    { *m = LongDocument{} }
func (m *LongDocument) String() string            { return proto.CompactTextString(m) }
func (*LongDocument) ProtoMessage()               {}
func (*LongDocument) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LongDocument) GetValue0() int64 {
	if m != nil {
		return m.Value0
	}
	return 0
}

func (m *LongDocument) GetValue1() int64 {
	if m != nil {
		return m.Value1
	}
	return 0
}

func (m *LongDocument) GetValue2() int64 {
	if m != nil {
		return m.Value2
	}
	return 0
}

func (m *LongDocument) GetValue3() int64 {
	if m != nil {
		return m.Value3
	}
	return 0
}

func (m *LongDocument) GetValue4() int64 {
	if m != nil {
		return m.Value4
	}
	return 0
}

func (m *LongDocument) GetValue5() int64 {
	if m != nil {
		return m.Value5
	}
	return 0
}

func (m *LongDocument) GetValue6() int64 {
	if m != nil {
		return m.Value6
	}
	return 0
}

func (m *LongDocument) GetValue7() int64 {
	if m != nil {
		return m.Value7
	}
	return 0
}

func (m *LongDocument) GetValue8() int64 {
	if m != nil {
		return m.Value8
	}
	return 0
}

func (m *LongDocument) GetValue9() int64 {
	if m != nil {
		return m.Value9
	}
	return 0
}

func (m *LongDocument) GetValueA() int64 {
	if m != nil {
		return m.ValueA
	}
	return 0
}

func (m *LongDocument) GetValueB() int64 {
	if m != nil {
		return m.ValueB
	}
	return 0
}

func (m *LongDocument) GetValueC() int64 {
	if m != nil {
		return m.ValueC
	}
	return 0
}

func (m *LongDocument) GetValueD() int64 {
	if m != nil {
		return m.ValueD
	}
	return 0
}

func (m *LongDocument) GetValueE() int64 {
	if m != nil {
		return m.ValueE
	}
	return 0
}

type SaltedLongDocument struct {
	Value0 []byte `protobuf:"bytes,16,opt,name=Value0,proto3" json:"Value0,omitempty"`
	Value1 []byte `protobuf:"bytes,1,opt,name=Value1,proto3" json:"Value1,omitempty"`
	Value2 []byte `protobuf:"bytes,2,opt,name=Value2,proto3" json:"Value2,omitempty"`
	Value3 []byte `protobuf:"bytes,3,opt,name=Value3,proto3" json:"Value3,omitempty"`
	Value4 []byte `protobuf:"bytes,4,opt,name=Value4,proto3" json:"Value4,omitempty"`
	Value5 []byte `protobuf:"bytes,5,opt,name=Value5,proto3" json:"Value5,omitempty"`
	Value6 []byte `protobuf:"bytes,6,opt,name=Value6,proto3" json:"Value6,omitempty"`
	Value7 []byte `protobuf:"bytes,7,opt,name=Value7,proto3" json:"Value7,omitempty"`
	Value8 []byte `protobuf:"bytes,8,opt,name=Value8,proto3" json:"Value8,omitempty"`
	Value9 []byte `protobuf:"bytes,9,opt,name=Value9,proto3" json:"Value9,omitempty"`
	ValueA []byte `protobuf:"bytes,10,opt,name=ValueA,proto3" json:"ValueA,omitempty"`
	ValueB []byte `protobuf:"bytes,11,opt,name=ValueB,proto3" json:"ValueB,omitempty"`
	ValueC []byte `protobuf:"bytes,12,opt,name=ValueC,proto3" json:"ValueC,omitempty"`
	ValueD []byte `protobuf:"bytes,13,opt,name=ValueD,proto3" json:"ValueD,omitempty"`
	ValueE []byte `protobuf:"bytes,14,opt,name=ValueE,proto3" json:"ValueE,omitempty"`
}

func (m *SaltedLongDocument) Reset()                    { *m = SaltedLongDocument{} }
func (m *SaltedLongDocument) String() string            { return proto.CompactTextString(m) }
func (*SaltedLongDocument) ProtoMessage()               {}
func (*SaltedLongDocument) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SaltedLongDocument) GetValue0() []byte {
	if m != nil {
		return m.Value0
	}
	return nil
}

func (m *SaltedLongDocument) GetValue1() []byte {
	if m != nil {
		return m.Value1
	}
	return nil
}

func (m *SaltedLongDocument) GetValue2() []byte {
	if m != nil {
		return m.Value2
	}
	return nil
}

func (m *SaltedLongDocument) GetValue3() []byte {
	if m != nil {
		return m.Value3
	}
	return nil
}

func (m *SaltedLongDocument) GetValue4() []byte {
	if m != nil {
		return m.Value4
	}
	return nil
}

func (m *SaltedLongDocument) GetValue5() []byte {
	if m != nil {
		return m.Value5
	}
	return nil
}

func (m *SaltedLongDocument) GetValue6() []byte {
	if m != nil {
		return m.Value6
	}
	return nil
}

func (m *SaltedLongDocument) GetValue7() []byte {
	if m != nil {
		return m.Value7
	}
	return nil
}

func (m *SaltedLongDocument) GetValue8() []byte {
	if m != nil {
		return m.Value8
	}
	return nil
}

func (m *SaltedLongDocument) GetValue9() []byte {
	if m != nil {
		return m.Value9
	}
	return nil
}

func (m *SaltedLongDocument) GetValueA() []byte {
	if m != nil {
		return m.ValueA
	}
	return nil
}

func (m *SaltedLongDocument) GetValueB() []byte {
	if m != nil {
		return m.ValueB
	}
	return nil
}

func (m *SaltedLongDocument) GetValueC() []byte {
	if m != nil {
		return m.ValueC
	}
	return nil
}

func (m *SaltedLongDocument) GetValueD() []byte {
	if m != nil {
		return m.ValueD
	}
	return nil
}

func (m *SaltedLongDocument) GetValueE() []byte {
	if m != nil {
		return m.ValueE
	}
	return nil
}

type SaltedExampleDocument struct {
	ValueA      []byte `protobuf:"bytes,1,opt,name=ValueA,proto3" json:"ValueA,omitempty"`
	ValueB      []byte `protobuf:"bytes,2,opt,name=ValueB,proto3" json:"ValueB,omitempty"`
	Value1      []byte `protobuf:"bytes,3,opt,name=Value1,proto3" json:"Value1,omitempty"`
	Value2      []byte `protobuf:"bytes,4,opt,name=Value2,proto3" json:"Value2,omitempty"`
	ValueBytes1 []byte `protobuf:"bytes,5,opt,name=ValueBytes1,proto3" json:"ValueBytes1,omitempty"`
}

func (m *SaltedExampleDocument) Reset()                    { *m = SaltedExampleDocument{} }
func (m *SaltedExampleDocument) String() string            { return proto.CompactTextString(m) }
func (*SaltedExampleDocument) ProtoMessage()               {}
func (*SaltedExampleDocument) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SaltedExampleDocument) GetValueA() []byte {
	if m != nil {
		return m.ValueA
	}
	return nil
}

func (m *SaltedExampleDocument) GetValueB() []byte {
	if m != nil {
		return m.ValueB
	}
	return nil
}

func (m *SaltedExampleDocument) GetValue1() []byte {
	if m != nil {
		return m.Value1
	}
	return nil
}

func (m *SaltedExampleDocument) GetValue2() []byte {
	if m != nil {
		return m.Value2
	}
	return nil
}

func (m *SaltedExampleDocument) GetValueBytes1() []byte {
	if m != nil {
		return m.ValueBytes1
	}
	return nil
}

func init() {
	proto.RegisterType((*ExampleDocument)(nil), "example.ExampleDocument")
	proto.RegisterType((*LongDocument)(nil), "example.LongDocument")
	proto.RegisterType((*SaltedLongDocument)(nil), "example.SaltedLongDocument")
	proto.RegisterType((*SaltedExampleDocument)(nil), "example.SaltedExampleDocument")
}

func init() { proto.RegisterFile("example.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 356 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0xd4, 0x3b, 0x4f, 0xc2, 0x50,
	0x14, 0xc0, 0xf1, 0xdc, 0xa2, 0x20, 0x97, 0x83, 0x9a, 0x26, 0x9a, 0x33, 0x36, 0x4c, 0x2c, 0x52,
	0xca, 0x9b, 0x51, 0x1e, 0x83, 0x89, 0x13, 0x26, 0x0e, 0x6e, 0x50, 0xaf, 0x48, 0xec, 0x83, 0x60,
	0x9b, 0xe0, 0xe7, 0x70, 0xf2, 0x8b, 0x3a, 0x39, 0x18, 0xa1, 0x1c, 0x0f, 0x31, 0x87, 0xb8, 0xd1,
	0x5f, 0x42, 0xef, 0xc9, 0xff, 0xe6, 0x54, 0x97, 0xcd, 0x7a, 0x1a, 0x2e, 0x03, 0x53, 0x5b, 0xae,
	0xe2, 0x24, 0xb6, 0x0b, 0xd9, 0x63, 0xe5, 0x5d, 0xe9, 0xb3, 0xf1, 0xf6, 0xf7, 0x28, 0xf6, 0xd3,
	0xd0, 0x44, 0x89, 0x7d, 0xa9, 0xf3, 0xf7, 0xd3, 0x20, 0x35, 0xd7, 0xa8, 0x1c, 0x55, 0x2d, 0x4e,
	0xb2, 0x27, 0xf2, 0x01, 0x5a, 0xcc, 0x07, 0xe4, 0x1e, 0xe6, 0x1c, 0x55, 0xcd, 0x65, 0xee, 0x91,
	0x37, 0xf0, 0x88, 0x79, 0xc3, 0x76, 0x74, 0x69, 0xfb, 0xcf, 0xb7, 0xc4, 0xbc, 0x7a, 0x78, 0xec,
	0xa8, 0x2a, 0x4c, 0x38, 0x55, 0x3e, 0x2d, 0x0d, 0xb7, 0x71, 0x34, 0xff, 0x33, 0x52, 0x1d, 0xcf,
	0xd9, 0xab, 0xea, 0xec, 0x68, 0x25, 0x1c, 0x6d, 0xed, 0x1d, 0xbd, 0xf3, 0xe6, 0xde, 0xa8, 0x4d,
	0xf2, 0xd6, 0xde, 0xa8, 0x2d, 0xf2, 0xf6, 0x66, 0xca, 0x9d, 0xb7, 0xc9, 0x3b, 0x98, 0x67, 0xde,
	0x21, 0xef, 0x62, 0x81, 0x79, 0x97, 0xbc, 0x87, 0x27, 0xcc, 0x7b, 0xe4, 0x7d, 0x2c, 0x32, 0xef,
	0xb3, 0x2b, 0xd0, 0xcc, 0xf9, 0x15, 0x94, 0x98, 0xff, 0x5e, 0xc1, 0x10, 0x81, 0xf9, 0x90, 0x7c,
	0x84, 0x65, 0xe6, 0x23, 0xf2, 0x31, 0x9e, 0x32, 0x1f, 0x57, 0xbe, 0x2c, 0x6d, 0xdf, 0x4d, 0x83,
	0xc4, 0x3c, 0x1e, 0xc8, 0x0f, 0x42, 0x7e, 0x10, 0xf2, 0x83, 0x90, 0x1f, 0x84, 0xfc, 0x20, 0xe4,
	0x07, 0x21, 0x3f, 0x08, 0xf9, 0x41, 0xc8, 0x0f, 0x42, 0x7e, 0x10, 0xf2, 0x83, 0x90, 0x1f, 0x84,
	0xfc, 0x20, 0xe4, 0x07, 0x21, 0x3f, 0x50, 0xfe, 0x0f, 0xa5, 0x2f, 0xb6, 0xf9, 0x0f, 0xef, 0x24,
	0x08, 0x3b, 0x09, 0xc2, 0x4e, 0x82, 0xb0, 0x93, 0xf0, 0xff, 0x9d, 0x1c, 0x78, 0x0f, 0xee, 0x7c,
	0x91, 0x3c, 0xa7, 0xb3, 0x9a, 0x1f, 0x87, 0xee, 0xd0, 0x44, 0xc9, 0x6a, 0xf1, 0x94, 0xce, 0xcd,
	0x4d, 0xe4, 0xbb, 0x7e, 0xfc, 0x33, 0xec, 0xfa, 0x2a, 0x34, 0xab, 0x97, 0xc0, 0xb8, 0xd9, 0xc7,
	0x65, 0x96, 0xdf, 0x7c, 0x6c, 0x9a, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x99, 0xa5, 0x6a, 0x7f,
	0x7d, 0x04, 0x00, 0x00,
}
