// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proofs/proto/proof.proto

package proofspb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MerkleHash struct {
	Left                 []byte   `protobuf:"bytes,1,opt,name=left,proto3" json:"left,omitempty"`
	Right                []byte   `protobuf:"bytes,2,opt,name=right,proto3" json:"right,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerkleHash) Reset()         { *m = MerkleHash{} }
func (m *MerkleHash) String() string { return proto.CompactTextString(m) }
func (*MerkleHash) ProtoMessage()    {}
func (*MerkleHash) Descriptor() ([]byte, []int) {
	return fileDescriptor_48dd2c57ca80438f, []int{0}
}

func (m *MerkleHash) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerkleHash.Unmarshal(m, b)
}
func (m *MerkleHash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerkleHash.Marshal(b, m, deterministic)
}
func (m *MerkleHash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerkleHash.Merge(m, src)
}
func (m *MerkleHash) XXX_Size() int {
	return xxx_messageInfo_MerkleHash.Size(m)
}
func (m *MerkleHash) XXX_DiscardUnknown() {
	xxx_messageInfo_MerkleHash.DiscardUnknown(m)
}

var xxx_messageInfo_MerkleHash proto.InternalMessageInfo

func (m *MerkleHash) GetLeft() []byte {
	if m != nil {
		return m.Left
	}
	return nil
}

func (m *MerkleHash) GetRight() []byte {
	if m != nil {
		return m.Right
	}
	return nil
}

type Proof struct {
	// Types that are valid to be assigned to Property:
	//	*Proof_ReadableName
	//	*Proof_CompactName
	Property isProof_Property `protobuf_oneof:"property"`
	Value    []byte           `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Salt     []byte           `protobuf:"bytes,3,opt,name=salt,proto3" json:"salt,omitempty"`
	// hash is filled if value & salt are not available
	Hash []byte `protobuf:"bytes,6,opt,name=hash,proto3" json:"hash,omitempty"`
	// Fills either 'hashes' for standard Merkle trees or 'sorted_hashes' for a lexicograhical ordered of a node hash
	// not both
	Hashes               []*MerkleHash `protobuf:"bytes,4,rep,name=hashes,proto3" json:"hashes,omitempty"`
	SortedHashes         [][]byte      `protobuf:"bytes,5,rep,name=sorted_hashes,json=sortedHashes,proto3" json:"sorted_hashes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Proof) Reset()         { *m = Proof{} }
func (m *Proof) String() string { return proto.CompactTextString(m) }
func (*Proof) ProtoMessage()    {}
func (*Proof) Descriptor() ([]byte, []int) {
	return fileDescriptor_48dd2c57ca80438f, []int{1}
}

func (m *Proof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Proof.Unmarshal(m, b)
}
func (m *Proof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Proof.Marshal(b, m, deterministic)
}
func (m *Proof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proof.Merge(m, src)
}
func (m *Proof) XXX_Size() int {
	return xxx_messageInfo_Proof.Size(m)
}
func (m *Proof) XXX_DiscardUnknown() {
	xxx_messageInfo_Proof.DiscardUnknown(m)
}

var xxx_messageInfo_Proof proto.InternalMessageInfo

type isProof_Property interface {
	isProof_Property()
}

type Proof_ReadableName struct {
	ReadableName string `protobuf:"bytes,7,opt,name=readable_name,json=readableName,proto3,oneof"`
}

type Proof_CompactName struct {
	CompactName []byte `protobuf:"bytes,9,opt,name=compact_name,json=compactName,proto3,oneof"`
}

func (*Proof_ReadableName) isProof_Property() {}

func (*Proof_CompactName) isProof_Property() {}

func (m *Proof) GetProperty() isProof_Property {
	if m != nil {
		return m.Property
	}
	return nil
}

func (m *Proof) GetReadableName() string {
	if x, ok := m.GetProperty().(*Proof_ReadableName); ok {
		return x.ReadableName
	}
	return ""
}

func (m *Proof) GetCompactName() []byte {
	if x, ok := m.GetProperty().(*Proof_CompactName); ok {
		return x.CompactName
	}
	return nil
}

func (m *Proof) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Proof) GetSalt() []byte {
	if m != nil {
		return m.Salt
	}
	return nil
}

func (m *Proof) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Proof) GetHashes() []*MerkleHash {
	if m != nil {
		return m.Hashes
	}
	return nil
}

func (m *Proof) GetSortedHashes() [][]byte {
	if m != nil {
		return m.SortedHashes
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Proof) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Proof_ReadableName)(nil),
		(*Proof_CompactName)(nil),
	}
}

var E_ExcludeFromTree = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         2862100,
	Name:          "proofs.exclude_from_tree",
	Tag:           "varint,2862100,opt,name=exclude_from_tree",
	Filename:      "proofs/proto/proof.proto",
}

var E_HashedField = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         2862101,
	Name:          "proofs.hashed_field",
	Tag:           "varint,2862101,opt,name=hashed_field",
	Filename:      "proofs/proto/proof.proto",
}

var E_FieldLength = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*uint64)(nil),
	Field:         2862102,
	Name:          "proofs.field_length",
	Tag:           "varint,2862102,opt,name=field_length",
	Filename:      "proofs/proto/proof.proto",
}

var E_MappingKey = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         2862103,
	Name:          "proofs.mapping_key",
	Tag:           "bytes,2862103,opt,name=mapping_key",
	Filename:      "proofs/proto/proof.proto",
}

var E_AppendFields = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         2862104,
	Name:          "proofs.append_fields",
	Tag:           "varint,2862104,opt,name=append_fields",
	Filename:      "proofs/proto/proof.proto",
}

var E_NoSalt = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         2862105,
	Name:          "proofs.no_salt",
	Tag:           "varint,2862105,opt,name=no_salt",
	Filename:      "proofs/proto/proof.proto",
}

func init() {
	proto.RegisterType((*MerkleHash)(nil), "proofs.MerkleHash")
	proto.RegisterType((*Proof)(nil), "proofs.Proof")
	proto.RegisterExtension(E_ExcludeFromTree)
	proto.RegisterExtension(E_HashedField)
	proto.RegisterExtension(E_FieldLength)
	proto.RegisterExtension(E_MappingKey)
	proto.RegisterExtension(E_AppendFields)
	proto.RegisterExtension(E_NoSalt)
}

func init() { proto.RegisterFile("proofs/proto/proof.proto", fileDescriptor_48dd2c57ca80438f) }

var fileDescriptor_48dd2c57ca80438f = []byte{
	// 454 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xdd, 0x8a, 0xd3, 0x40,
	0x14, 0xc7, 0xb7, 0xb6, 0xcd, 0xb6, 0x27, 0x29, 0xe2, 0xb0, 0x17, 0x41, 0x10, 0xc2, 0xae, 0x42,
	0xf1, 0x22, 0x05, 0x05, 0xc1, 0xdc, 0x59, 0x71, 0x29, 0xb8, 0x6a, 0x89, 0x5e, 0x79, 0x13, 0xa6,
	0xc9, 0xc9, 0x07, 0x3b, 0xc9, 0x0c, 0x33, 0x53, 0xb1, 0xef, 0xe1, 0xe7, 0x4b, 0xf8, 0x3c, 0x3e,
	0x85, 0xcf, 0x20, 0x33, 0x93, 0xb0, 0x97, 0xb9, 0xca, 0x99, 0xff, 0x39, 0xff, 0xdf, 0x99, 0x73,
	0x26, 0x10, 0x0a, 0xc9, 0x79, 0xa9, 0x36, 0x42, 0x72, 0xcd, 0x37, 0xf6, 0x10, 0xdb, 0x98, 0x78,
	0x2e, 0xf3, 0x30, 0xaa, 0x38, 0xaf, 0x18, 0xba, 0x8a, 0xc3, 0xb1, 0xdc, 0x14, 0xa8, 0x72, 0xd9,
	0x08, 0xcd, 0xa5, 0xab, 0xbc, 0x7c, 0x01, 0xf0, 0x0e, 0xe5, 0x2d, 0xc3, 0x1d, 0x55, 0x35, 0x21,
	0x30, 0x63, 0x58, 0xea, 0x70, 0x12, 0x4d, 0xd6, 0x41, 0x6a, 0x63, 0x72, 0x01, 0x73, 0xd9, 0x54,
	0xb5, 0x0e, 0xef, 0x59, 0xd1, 0x1d, 0x2e, 0xff, 0x4d, 0x60, 0xbe, 0x37, 0x4d, 0xc8, 0x13, 0x58,
	0x49, 0xa4, 0x05, 0x3d, 0x30, 0xcc, 0x3a, 0xda, 0x62, 0x78, 0x1e, 0x4d, 0xd6, 0xcb, 0xdd, 0x59,
	0x1a, 0x0c, 0xf2, 0x7b, 0xda, 0x22, 0xb9, 0x82, 0x20, 0xe7, 0xad, 0xa0, 0xb9, 0x76, 0x55, 0x4b,
	0x43, 0xdb, 0x9d, 0xa5, 0x7e, 0xaf, 0xda, 0xa2, 0x0b, 0x98, 0x7f, 0xa1, 0xec, 0x88, 0x43, 0x2f,
	0x7b, 0x30, 0xb7, 0x52, 0x94, 0xe9, 0x70, 0xea, 0x6e, 0x65, 0x62, 0xa3, 0xd5, 0x54, 0xd5, 0xa1,
	0xe7, 0x34, 0x13, 0x93, 0xa7, 0xe0, 0x99, 0x2f, 0xaa, 0x70, 0x16, 0x4d, 0xd7, 0xfe, 0x33, 0x12,
	0xbb, 0x35, 0xc4, 0x77, 0x13, 0xa6, 0x7d, 0x05, 0xb9, 0x82, 0x95, 0xe2, 0x52, 0x63, 0x91, 0xf5,
	0x96, 0x79, 0x34, 0x5d, 0x07, 0x69, 0xe0, 0xc4, 0x9d, 0xd5, 0xb6, 0x00, 0x0b, 0x21, 0xb9, 0x40,
	0xa9, 0x4f, 0xc9, 0x0d, 0x3c, 0xc0, 0xaf, 0x39, 0x3b, 0x16, 0x98, 0x95, 0x92, 0xb7, 0x99, 0x96,
	0x88, 0xe4, 0x51, 0xec, 0x16, 0x1c, 0x0f, 0x0b, 0x8e, 0xaf, 0x1b, 0x64, 0xc5, 0x07, 0xa1, 0x1b,
	0xde, 0xa9, 0xf0, 0xdb, 0xdf, 0x3f, 0x66, 0x93, 0x8b, 0xf4, 0x7e, 0x6f, 0xbd, 0x96, 0xbc, 0xfd,
	0x24, 0x11, 0x93, 0xd7, 0x10, 0xd8, 0xbe, 0x45, 0x56, 0x1a, 0xc3, 0x18, 0xe8, 0xfb, 0x00, 0xf2,
	0x9d, 0xcb, 0x26, 0x0d, 0xc4, 0xba, 0x33, 0x86, 0x5d, 0xa5, 0xeb, 0x31, 0xc8, 0x0f, 0x07, 0x99,
	0xa5, 0xbe, 0x75, 0xdd, 0x58, 0x53, 0xf2, 0x0a, 0xfc, 0x96, 0x0a, 0xd1, 0x74, 0x55, 0x76, 0x8b,
	0xa7, 0x31, 0xc6, 0x4f, 0xc7, 0x58, 0xa6, 0xd0, 0x9b, 0xde, 0xe2, 0x29, 0x79, 0x03, 0x2b, 0x2a,
	0x04, 0x76, 0xfd, 0x30, 0x6a, 0x0c, 0xf2, 0x6b, 0x98, 0x26, 0x70, 0x36, 0x9b, 0x54, 0xc9, 0x4b,
	0x38, 0xef, 0x78, 0x66, 0x5f, 0x77, 0x04, 0xf0, 0x7b, 0x00, 0x78, 0x1d, 0xff, 0x48, 0x99, 0xde,
	0x3e, 0x06, 0xc8, 0x79, 0xdb, 0x3f, 0xf7, 0x16, 0xec, 0x8f, 0xb9, 0x37, 0xd6, 0xfd, 0xe4, 0xf3,
	0xc2, 0xa9, 0xe2, 0x70, 0xf0, 0x2c, 0xed, 0xf9, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6b, 0xfd,
	0xf7, 0xb3, 0x38, 0x03, 0x00, 0x00,
}
