// Code generated by protoc-gen-go. DO NOT EDIT.
// source: examples/documents/example.proto

package documentspb

import (
	fmt "fmt"
	proto1 "github.com/centrifuge/precise-proofs/proofs/proto"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Enum int32

const (
	Enum_type_one Enum = 0
	Enum_type_two Enum = 1
)

var Enum_name = map[int32]string{
	0: "type_one",
	1: "type_two",
}

var Enum_value = map[string]int32{
	"type_one": 0,
	"type_two": 1,
}

func (x Enum) String() string {
	return proto.EnumName(Enum_name, int32(x))
}

func (Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bbdf1f37afed577e, []int{0}
}

type ExampleDocument struct {
	ValueA               string         `protobuf:"bytes,1,opt,name=valueA,proto3" json:"valueA,omitempty"`
	ValueB               string         `protobuf:"bytes,2,opt,name=valueB,proto3" json:"valueB,omitempty"`
	Value1               int64          `protobuf:"varint,3,opt,name=value1,proto3" json:"value1,omitempty"`
	Value2               int64          `protobuf:"varint,4,opt,name=value2,proto3" json:"value2,omitempty"`
	ValueBytes1          []byte         `protobuf:"bytes,5,opt,name=value_bytes1,json=valueBytes1,proto3" json:"value_bytes1,omitempty"`
	ValueCamelCased      []byte         `protobuf:"bytes,6,opt,name=ValueCamelCased,proto3" json:"ValueCamelCased,omitempty"`
	ValueNotIgnored      []byte         `protobuf:"bytes,7,opt,name=value_not_ignored,json=valueNotIgnored,proto3" json:"value_not_ignored,omitempty"`
	ValueIgnored         []byte         `protobuf:"bytes,8,opt,name=value_ignored,json=valueIgnored,proto3" json:"value_ignored,omitempty"`
	ValueNotHashed       []byte         `protobuf:"bytes,9,opt,name=value_not_hashed,json=valueNotHashed,proto3" json:"value_not_hashed,omitempty"`
	EnumType             Enum           `protobuf:"varint,10,opt,name=enum_type,json=enumType,proto3,enum=documents.Enum" json:"enum_type,omitempty"`
	ValueBool            bool           `protobuf:"varint,12,opt,name=valueBool,proto3" json:"valueBool,omitempty"`
	Name                 *Name          `protobuf:"bytes,13,opt,name=name,proto3" json:"name,omitempty"`
	PaddingA             string         `protobuf:"bytes,14,opt,name=paddingA,proto3" json:"paddingA,omitempty"`
	PaddingB             []byte         `protobuf:"bytes,15,opt,name=paddingB,proto3" json:"paddingB,omitempty"`
	Salts                []*proto1.Salt `protobuf:"bytes,11,rep,name=salts,proto3" json:"salts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ExampleDocument) Reset()         { *m = ExampleDocument{} }
func (m *ExampleDocument) String() string { return proto.CompactTextString(m) }
func (*ExampleDocument) ProtoMessage()    {}
func (*ExampleDocument) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbdf1f37afed577e, []int{0}
}

func (m *ExampleDocument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExampleDocument.Unmarshal(m, b)
}
func (m *ExampleDocument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExampleDocument.Marshal(b, m, deterministic)
}
func (m *ExampleDocument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExampleDocument.Merge(m, src)
}
func (m *ExampleDocument) XXX_Size() int {
	return xxx_messageInfo_ExampleDocument.Size(m)
}
func (m *ExampleDocument) XXX_DiscardUnknown() {
	xxx_messageInfo_ExampleDocument.DiscardUnknown(m)
}

var xxx_messageInfo_ExampleDocument proto.InternalMessageInfo

func (m *ExampleDocument) GetValueA() string {
	if m != nil {
		return m.ValueA
	}
	return ""
}

func (m *ExampleDocument) GetValueB() string {
	if m != nil {
		return m.ValueB
	}
	return ""
}

func (m *ExampleDocument) GetValue1() int64 {
	if m != nil {
		return m.Value1
	}
	return 0
}

func (m *ExampleDocument) GetValue2() int64 {
	if m != nil {
		return m.Value2
	}
	return 0
}

func (m *ExampleDocument) GetValueBytes1() []byte {
	if m != nil {
		return m.ValueBytes1
	}
	return nil
}

func (m *ExampleDocument) GetValueCamelCased() []byte {
	if m != nil {
		return m.ValueCamelCased
	}
	return nil
}

func (m *ExampleDocument) GetValueNotIgnored() []byte {
	if m != nil {
		return m.ValueNotIgnored
	}
	return nil
}

func (m *ExampleDocument) GetValueIgnored() []byte {
	if m != nil {
		return m.ValueIgnored
	}
	return nil
}

func (m *ExampleDocument) GetValueNotHashed() []byte {
	if m != nil {
		return m.ValueNotHashed
	}
	return nil
}

func (m *ExampleDocument) GetEnumType() Enum {
	if m != nil {
		return m.EnumType
	}
	return Enum_type_one
}

func (m *ExampleDocument) GetValueBool() bool {
	if m != nil {
		return m.ValueBool
	}
	return false
}

func (m *ExampleDocument) GetName() *Name {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *ExampleDocument) GetPaddingA() string {
	if m != nil {
		return m.PaddingA
	}
	return ""
}

func (m *ExampleDocument) GetPaddingB() []byte {
	if m != nil {
		return m.PaddingB
	}
	return nil
}

func (m *ExampleDocument) GetSalts() []*proto1.Salt {
	if m != nil {
		return m.Salts
	}
	return nil
}

type AllFieldTypes struct {
	StringValue          string               `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3" json:"string_value,omitempty"`
	TimeStampValue       *timestamp.Timestamp `protobuf:"bytes,2,opt,name=time_stamp_value,json=timeStampValue,proto3" json:"time_stamp_value,omitempty"`
	Salts                []*proto1.Salt       `protobuf:"bytes,3,rep,name=salts,proto3" json:"salts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AllFieldTypes) Reset()         { *m = AllFieldTypes{} }
func (m *AllFieldTypes) String() string { return proto.CompactTextString(m) }
func (*AllFieldTypes) ProtoMessage()    {}
func (*AllFieldTypes) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbdf1f37afed577e, []int{1}
}

func (m *AllFieldTypes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllFieldTypes.Unmarshal(m, b)
}
func (m *AllFieldTypes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllFieldTypes.Marshal(b, m, deterministic)
}
func (m *AllFieldTypes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllFieldTypes.Merge(m, src)
}
func (m *AllFieldTypes) XXX_Size() int {
	return xxx_messageInfo_AllFieldTypes.Size(m)
}
func (m *AllFieldTypes) XXX_DiscardUnknown() {
	xxx_messageInfo_AllFieldTypes.DiscardUnknown(m)
}

var xxx_messageInfo_AllFieldTypes proto.InternalMessageInfo

func (m *AllFieldTypes) GetStringValue() string {
	if m != nil {
		return m.StringValue
	}
	return ""
}

func (m *AllFieldTypes) GetTimeStampValue() *timestamp.Timestamp {
	if m != nil {
		return m.TimeStampValue
	}
	return nil
}

func (m *AllFieldTypes) GetSalts() []*proto1.Salt {
	if m != nil {
		return m.Salts
	}
	return nil
}

type AllFieldTypesSalts struct {
	StringValue          []byte         `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3" json:"string_value,omitempty"`
	TimeStampValue       []byte         `protobuf:"bytes,2,opt,name=time_stamp_value,json=timeStampValue,proto3" json:"time_stamp_value,omitempty"`
	Salts                []*proto1.Salt `protobuf:"bytes,3,rep,name=salts,proto3" json:"salts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AllFieldTypesSalts) Reset()         { *m = AllFieldTypesSalts{} }
func (m *AllFieldTypesSalts) String() string { return proto.CompactTextString(m) }
func (*AllFieldTypesSalts) ProtoMessage()    {}
func (*AllFieldTypesSalts) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbdf1f37afed577e, []int{2}
}

func (m *AllFieldTypesSalts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllFieldTypesSalts.Unmarshal(m, b)
}
func (m *AllFieldTypesSalts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllFieldTypesSalts.Marshal(b, m, deterministic)
}
func (m *AllFieldTypesSalts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllFieldTypesSalts.Merge(m, src)
}
func (m *AllFieldTypesSalts) XXX_Size() int {
	return xxx_messageInfo_AllFieldTypesSalts.Size(m)
}
func (m *AllFieldTypesSalts) XXX_DiscardUnknown() {
	xxx_messageInfo_AllFieldTypesSalts.DiscardUnknown(m)
}

var xxx_messageInfo_AllFieldTypesSalts proto.InternalMessageInfo

func (m *AllFieldTypesSalts) GetStringValue() []byte {
	if m != nil {
		return m.StringValue
	}
	return nil
}

func (m *AllFieldTypesSalts) GetTimeStampValue() []byte {
	if m != nil {
		return m.TimeStampValue
	}
	return nil
}

func (m *AllFieldTypesSalts) GetSalts() []*proto1.Salt {
	if m != nil {
		return m.Salts
	}
	return nil
}

type SimpleItem struct {
	ValueA               string   `protobuf:"bytes,1,opt,name=valueA,proto3" json:"valueA,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleItem) Reset()         { *m = SimpleItem{} }
func (m *SimpleItem) String() string { return proto.CompactTextString(m) }
func (*SimpleItem) ProtoMessage()    {}
func (*SimpleItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbdf1f37afed577e, []int{3}
}

func (m *SimpleItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleItem.Unmarshal(m, b)
}
func (m *SimpleItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleItem.Marshal(b, m, deterministic)
}
func (m *SimpleItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleItem.Merge(m, src)
}
func (m *SimpleItem) XXX_Size() int {
	return xxx_messageInfo_SimpleItem.Size(m)
}
func (m *SimpleItem) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleItem.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleItem proto.InternalMessageInfo

func (m *SimpleItem) GetValueA() string {
	if m != nil {
		return m.ValueA
	}
	return ""
}

type RepeatedItem struct {
	ValueA               []*SimpleItem  `protobuf:"bytes,1,rep,name=valueA,proto3" json:"valueA,omitempty"`
	ValueB               string         `protobuf:"bytes,2,opt,name=valueB,proto3" json:"valueB,omitempty"`
	Salts                []*proto1.Salt `protobuf:"bytes,3,rep,name=salts,proto3" json:"salts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RepeatedItem) Reset()         { *m = RepeatedItem{} }
func (m *RepeatedItem) String() string { return proto.CompactTextString(m) }
func (*RepeatedItem) ProtoMessage()    {}
func (*RepeatedItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbdf1f37afed577e, []int{4}
}

func (m *RepeatedItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepeatedItem.Unmarshal(m, b)
}
func (m *RepeatedItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepeatedItem.Marshal(b, m, deterministic)
}
func (m *RepeatedItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepeatedItem.Merge(m, src)
}
func (m *RepeatedItem) XXX_Size() int {
	return xxx_messageInfo_RepeatedItem.Size(m)
}
func (m *RepeatedItem) XXX_DiscardUnknown() {
	xxx_messageInfo_RepeatedItem.DiscardUnknown(m)
}

var xxx_messageInfo_RepeatedItem proto.InternalMessageInfo

func (m *RepeatedItem) GetValueA() []*SimpleItem {
	if m != nil {
		return m.ValueA
	}
	return nil
}

func (m *RepeatedItem) GetValueB() string {
	if m != nil {
		return m.ValueB
	}
	return ""
}

func (m *RepeatedItem) GetSalts() []*proto1.Salt {
	if m != nil {
		return m.Salts
	}
	return nil
}

type SimpleMap struct {
	Value                map[int32]string `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SimpleMap) Reset()         { *m = SimpleMap{} }
func (m *SimpleMap) String() string { return proto.CompactTextString(m) }
func (*SimpleMap) ProtoMessage()    {}
func (*SimpleMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbdf1f37afed577e, []int{5}
}

func (m *SimpleMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleMap.Unmarshal(m, b)
}
func (m *SimpleMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleMap.Marshal(b, m, deterministic)
}
func (m *SimpleMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleMap.Merge(m, src)
}
func (m *SimpleMap) XXX_Size() int {
	return xxx_messageInfo_SimpleMap.Size(m)
}
func (m *SimpleMap) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleMap.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleMap proto.InternalMessageInfo

func (m *SimpleMap) GetValue() map[int32]string {
	if m != nil {
		return m.Value
	}
	return nil
}

type SimpleStringMap struct {
	Value                map[string]string `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Salts                []*proto1.Salt    `protobuf:"bytes,2,rep,name=salts,proto3" json:"salts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SimpleStringMap) Reset()         { *m = SimpleStringMap{} }
func (m *SimpleStringMap) String() string { return proto.CompactTextString(m) }
func (*SimpleStringMap) ProtoMessage()    {}
func (*SimpleStringMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbdf1f37afed577e, []int{6}
}

func (m *SimpleStringMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleStringMap.Unmarshal(m, b)
}
func (m *SimpleStringMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleStringMap.Marshal(b, m, deterministic)
}
func (m *SimpleStringMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleStringMap.Merge(m, src)
}
func (m *SimpleStringMap) XXX_Size() int {
	return xxx_messageInfo_SimpleStringMap.Size(m)
}
func (m *SimpleStringMap) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleStringMap.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleStringMap proto.InternalMessageInfo

func (m *SimpleStringMap) GetValue() map[string]string {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *SimpleStringMap) GetSalts() []*proto1.Salt {
	if m != nil {
		return m.Salts
	}
	return nil
}

type NestedMap struct {
	Value                map[int32]*SimpleMap `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Salts                []*proto1.Salt       `protobuf:"bytes,2,rep,name=salts,proto3" json:"salts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *NestedMap) Reset()         { *m = NestedMap{} }
func (m *NestedMap) String() string { return proto.CompactTextString(m) }
func (*NestedMap) ProtoMessage()    {}
func (*NestedMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbdf1f37afed577e, []int{7}
}

func (m *NestedMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NestedMap.Unmarshal(m, b)
}
func (m *NestedMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NestedMap.Marshal(b, m, deterministic)
}
func (m *NestedMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NestedMap.Merge(m, src)
}
func (m *NestedMap) XXX_Size() int {
	return xxx_messageInfo_NestedMap.Size(m)
}
func (m *NestedMap) XXX_DiscardUnknown() {
	xxx_messageInfo_NestedMap.DiscardUnknown(m)
}

var xxx_messageInfo_NestedMap proto.InternalMessageInfo

func (m *NestedMap) GetValue() map[int32]*SimpleMap {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *NestedMap) GetSalts() []*proto1.Salt {
	if m != nil {
		return m.Salts
	}
	return nil
}

type SimpleEntry struct {
	EntryKey             string   `protobuf:"bytes,1,opt,name=entry_key,json=entryKey,proto3" json:"entry_key,omitempty"`
	EntryValue           string   `protobuf:"bytes,2,opt,name=entry_value,json=entryValue,proto3" json:"entry_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleEntry) Reset()         { *m = SimpleEntry{} }
func (m *SimpleEntry) String() string { return proto.CompactTextString(m) }
func (*SimpleEntry) ProtoMessage()    {}
func (*SimpleEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbdf1f37afed577e, []int{8}
}

func (m *SimpleEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleEntry.Unmarshal(m, b)
}
func (m *SimpleEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleEntry.Marshal(b, m, deterministic)
}
func (m *SimpleEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleEntry.Merge(m, src)
}
func (m *SimpleEntry) XXX_Size() int {
	return xxx_messageInfo_SimpleEntry.Size(m)
}
func (m *SimpleEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleEntry.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleEntry proto.InternalMessageInfo

func (m *SimpleEntry) GetEntryKey() string {
	if m != nil {
		return m.EntryKey
	}
	return ""
}

func (m *SimpleEntry) GetEntryValue() string {
	if m != nil {
		return m.EntryValue
	}
	return ""
}

type SimpleEntries struct {
	Entries              []*SimpleEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Salts                []*proto1.Salt `protobuf:"bytes,2,rep,name=salts,proto3" json:"salts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SimpleEntries) Reset()         { *m = SimpleEntries{} }
func (m *SimpleEntries) String() string { return proto.CompactTextString(m) }
func (*SimpleEntries) ProtoMessage()    {}
func (*SimpleEntries) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbdf1f37afed577e, []int{9}
}

func (m *SimpleEntries) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleEntries.Unmarshal(m, b)
}
func (m *SimpleEntries) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleEntries.Marshal(b, m, deterministic)
}
func (m *SimpleEntries) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleEntries.Merge(m, src)
}
func (m *SimpleEntries) XXX_Size() int {
	return xxx_messageInfo_SimpleEntries.Size(m)
}
func (m *SimpleEntries) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleEntries.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleEntries proto.InternalMessageInfo

func (m *SimpleEntries) GetEntries() []*SimpleEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *SimpleEntries) GetSalts() []*proto1.Salt {
	if m != nil {
		return m.Salts
	}
	return nil
}

type Entry struct {
	EntryKey             string   `protobuf:"bytes,1,opt,name=entry_key,json=entryKey,proto3" json:"entry_key,omitempty"`
	ValueA               string   `protobuf:"bytes,2,opt,name=valueA,proto3" json:"valueA,omitempty"`
	ValueB               []byte   `protobuf:"bytes,3,opt,name=valueB,proto3" json:"valueB,omitempty"`
	ValueC               int64    `protobuf:"varint,4,opt,name=valueC,proto3" json:"valueC,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbdf1f37afed577e, []int{10}
}

func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (m *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(m, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetEntryKey() string {
	if m != nil {
		return m.EntryKey
	}
	return ""
}

func (m *Entry) GetValueA() string {
	if m != nil {
		return m.ValueA
	}
	return ""
}

func (m *Entry) GetValueB() []byte {
	if m != nil {
		return m.ValueB
	}
	return nil
}

func (m *Entry) GetValueC() int64 {
	if m != nil {
		return m.ValueC
	}
	return 0
}

type Entries struct {
	Entries              []*Entry       `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Salts                []*proto1.Salt `protobuf:"bytes,2,rep,name=salts,proto3" json:"salts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Entries) Reset()         { *m = Entries{} }
func (m *Entries) String() string { return proto.CompactTextString(m) }
func (*Entries) ProtoMessage()    {}
func (*Entries) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbdf1f37afed577e, []int{11}
}

func (m *Entries) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entries.Unmarshal(m, b)
}
func (m *Entries) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entries.Marshal(b, m, deterministic)
}
func (m *Entries) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entries.Merge(m, src)
}
func (m *Entries) XXX_Size() int {
	return xxx_messageInfo_Entries.Size(m)
}
func (m *Entries) XXX_DiscardUnknown() {
	xxx_messageInfo_Entries.DiscardUnknown(m)
}

var xxx_messageInfo_Entries proto.InternalMessageInfo

func (m *Entries) GetEntries() []*Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *Entries) GetSalts() []*proto1.Salt {
	if m != nil {
		return m.Salts
	}
	return nil
}

type BytesKeyEntry struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BytesKeyEntry) Reset()         { *m = BytesKeyEntry{} }
func (m *BytesKeyEntry) String() string { return proto.CompactTextString(m) }
func (*BytesKeyEntry) ProtoMessage()    {}
func (*BytesKeyEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbdf1f37afed577e, []int{12}
}

func (m *BytesKeyEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BytesKeyEntry.Unmarshal(m, b)
}
func (m *BytesKeyEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BytesKeyEntry.Marshal(b, m, deterministic)
}
func (m *BytesKeyEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BytesKeyEntry.Merge(m, src)
}
func (m *BytesKeyEntry) XXX_Size() int {
	return xxx_messageInfo_BytesKeyEntry.Size(m)
}
func (m *BytesKeyEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_BytesKeyEntry.DiscardUnknown(m)
}

var xxx_messageInfo_BytesKeyEntry proto.InternalMessageInfo

func (m *BytesKeyEntry) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *BytesKeyEntry) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type BytesKeyEntries struct {
	Entries              []*BytesKeyEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Salts                []*proto1.Salt   `protobuf:"bytes,2,rep,name=salts,proto3" json:"salts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *BytesKeyEntries) Reset()         { *m = BytesKeyEntries{} }
func (m *BytesKeyEntries) String() string { return proto.CompactTextString(m) }
func (*BytesKeyEntries) ProtoMessage()    {}
func (*BytesKeyEntries) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbdf1f37afed577e, []int{13}
}

func (m *BytesKeyEntries) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BytesKeyEntries.Unmarshal(m, b)
}
func (m *BytesKeyEntries) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BytesKeyEntries.Marshal(b, m, deterministic)
}
func (m *BytesKeyEntries) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BytesKeyEntries.Merge(m, src)
}
func (m *BytesKeyEntries) XXX_Size() int {
	return xxx_messageInfo_BytesKeyEntries.Size(m)
}
func (m *BytesKeyEntries) XXX_DiscardUnknown() {
	xxx_messageInfo_BytesKeyEntries.DiscardUnknown(m)
}

var xxx_messageInfo_BytesKeyEntries proto.InternalMessageInfo

func (m *BytesKeyEntries) GetEntries() []*BytesKeyEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *BytesKeyEntries) GetSalts() []*proto1.Salt {
	if m != nil {
		return m.Salts
	}
	return nil
}

type TwoLevelRepeatedDocument struct {
	ValueA               string          `protobuf:"bytes,1,opt,name=valueA,proto3" json:"valueA,omitempty"`
	ValueB               []*RepeatedItem `protobuf:"bytes,2,rep,name=valueB,proto3" json:"valueB,omitempty"`
	Salts                []*proto1.Salt  `protobuf:"bytes,3,rep,name=salts,proto3" json:"salts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *TwoLevelRepeatedDocument) Reset()         { *m = TwoLevelRepeatedDocument{} }
func (m *TwoLevelRepeatedDocument) String() string { return proto.CompactTextString(m) }
func (*TwoLevelRepeatedDocument) ProtoMessage()    {}
func (*TwoLevelRepeatedDocument) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbdf1f37afed577e, []int{14}
}

func (m *TwoLevelRepeatedDocument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TwoLevelRepeatedDocument.Unmarshal(m, b)
}
func (m *TwoLevelRepeatedDocument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TwoLevelRepeatedDocument.Marshal(b, m, deterministic)
}
func (m *TwoLevelRepeatedDocument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TwoLevelRepeatedDocument.Merge(m, src)
}
func (m *TwoLevelRepeatedDocument) XXX_Size() int {
	return xxx_messageInfo_TwoLevelRepeatedDocument.Size(m)
}
func (m *TwoLevelRepeatedDocument) XXX_DiscardUnknown() {
	xxx_messageInfo_TwoLevelRepeatedDocument.DiscardUnknown(m)
}

var xxx_messageInfo_TwoLevelRepeatedDocument proto.InternalMessageInfo

func (m *TwoLevelRepeatedDocument) GetValueA() string {
	if m != nil {
		return m.ValueA
	}
	return ""
}

func (m *TwoLevelRepeatedDocument) GetValueB() []*RepeatedItem {
	if m != nil {
		return m.ValueB
	}
	return nil
}

func (m *TwoLevelRepeatedDocument) GetSalts() []*proto1.Salt {
	if m != nil {
		return m.Salts
	}
	return nil
}

type SimpleRepeatedDocument struct {
	ValueA               string         `protobuf:"bytes,1,opt,name=valueA,proto3" json:"valueA,omitempty"`
	ValueB               string         `protobuf:"bytes,2,opt,name=valueB,proto3" json:"valueB,omitempty"`
	ValueC               []string       `protobuf:"bytes,3,rep,name=valueC,proto3" json:"valueC,omitempty"`
	Salts                []*proto1.Salt `protobuf:"bytes,4,rep,name=salts,proto3" json:"salts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SimpleRepeatedDocument) Reset()         { *m = SimpleRepeatedDocument{} }
func (m *SimpleRepeatedDocument) String() string { return proto.CompactTextString(m) }
func (*SimpleRepeatedDocument) ProtoMessage()    {}
func (*SimpleRepeatedDocument) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbdf1f37afed577e, []int{15}
}

func (m *SimpleRepeatedDocument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleRepeatedDocument.Unmarshal(m, b)
}
func (m *SimpleRepeatedDocument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleRepeatedDocument.Marshal(b, m, deterministic)
}
func (m *SimpleRepeatedDocument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleRepeatedDocument.Merge(m, src)
}
func (m *SimpleRepeatedDocument) XXX_Size() int {
	return xxx_messageInfo_SimpleRepeatedDocument.Size(m)
}
func (m *SimpleRepeatedDocument) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleRepeatedDocument.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleRepeatedDocument proto.InternalMessageInfo

func (m *SimpleRepeatedDocument) GetValueA() string {
	if m != nil {
		return m.ValueA
	}
	return ""
}

func (m *SimpleRepeatedDocument) GetValueB() string {
	if m != nil {
		return m.ValueB
	}
	return ""
}

func (m *SimpleRepeatedDocument) GetValueC() []string {
	if m != nil {
		return m.ValueC
	}
	return nil
}

func (m *SimpleRepeatedDocument) GetSalts() []*proto1.Salt {
	if m != nil {
		return m.Salts
	}
	return nil
}

type SimpleMapDocument struct {
	ValueA               string            `protobuf:"bytes,1,opt,name=valueA,proto3" json:"valueA,omitempty"`
	ValueB               string            `protobuf:"bytes,2,opt,name=valueB,proto3" json:"valueB,omitempty"`
	ValueC               map[string]string `protobuf:"bytes,3,rep,name=valueC,proto3" json:"valueC,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ValueD               map[int32]string  `protobuf:"bytes,4,rep,name=valueD,proto3" json:"valueD,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Salts                []*proto1.Salt    `protobuf:"bytes,5,rep,name=salts,proto3" json:"salts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SimpleMapDocument) Reset()         { *m = SimpleMapDocument{} }
func (m *SimpleMapDocument) String() string { return proto.CompactTextString(m) }
func (*SimpleMapDocument) ProtoMessage()    {}
func (*SimpleMapDocument) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbdf1f37afed577e, []int{16}
}

func (m *SimpleMapDocument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleMapDocument.Unmarshal(m, b)
}
func (m *SimpleMapDocument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleMapDocument.Marshal(b, m, deterministic)
}
func (m *SimpleMapDocument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleMapDocument.Merge(m, src)
}
func (m *SimpleMapDocument) XXX_Size() int {
	return xxx_messageInfo_SimpleMapDocument.Size(m)
}
func (m *SimpleMapDocument) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleMapDocument.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleMapDocument proto.InternalMessageInfo

func (m *SimpleMapDocument) GetValueA() string {
	if m != nil {
		return m.ValueA
	}
	return ""
}

func (m *SimpleMapDocument) GetValueB() string {
	if m != nil {
		return m.ValueB
	}
	return ""
}

func (m *SimpleMapDocument) GetValueC() map[string]string {
	if m != nil {
		return m.ValueC
	}
	return nil
}

func (m *SimpleMapDocument) GetValueD() map[int32]string {
	if m != nil {
		return m.ValueD
	}
	return nil
}

func (m *SimpleMapDocument) GetSalts() []*proto1.Salt {
	if m != nil {
		return m.Salts
	}
	return nil
}

type TwoLevelItem struct {
	ValueA               *SimpleItem    `protobuf:"bytes,1,opt,name=valueA,proto3" json:"valueA,omitempty"`
	ValueB               string         `protobuf:"bytes,2,opt,name=valueB,proto3" json:"valueB,omitempty"`
	Salts                []*proto1.Salt `protobuf:"bytes,3,rep,name=salts,proto3" json:"salts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TwoLevelItem) Reset()         { *m = TwoLevelItem{} }
func (m *TwoLevelItem) String() string { return proto.CompactTextString(m) }
func (*TwoLevelItem) ProtoMessage()    {}
func (*TwoLevelItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbdf1f37afed577e, []int{17}
}

func (m *TwoLevelItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TwoLevelItem.Unmarshal(m, b)
}
func (m *TwoLevelItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TwoLevelItem.Marshal(b, m, deterministic)
}
func (m *TwoLevelItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TwoLevelItem.Merge(m, src)
}
func (m *TwoLevelItem) XXX_Size() int {
	return xxx_messageInfo_TwoLevelItem.Size(m)
}
func (m *TwoLevelItem) XXX_DiscardUnknown() {
	xxx_messageInfo_TwoLevelItem.DiscardUnknown(m)
}

var xxx_messageInfo_TwoLevelItem proto.InternalMessageInfo

func (m *TwoLevelItem) GetValueA() *SimpleItem {
	if m != nil {
		return m.ValueA
	}
	return nil
}

func (m *TwoLevelItem) GetValueB() string {
	if m != nil {
		return m.ValueB
	}
	return ""
}

func (m *TwoLevelItem) GetSalts() []*proto1.Salt {
	if m != nil {
		return m.Salts
	}
	return nil
}

type NestedRepeatedDocument struct {
	ValueA               string         `protobuf:"bytes,1,opt,name=valueA,proto3" json:"valueA,omitempty"`
	ValueB               string         `protobuf:"bytes,2,opt,name=valueB,proto3" json:"valueB,omitempty"`
	ValueC               []*SimpleItem  `protobuf:"bytes,3,rep,name=valueC,proto3" json:"valueC,omitempty"`
	ValueD               *TwoLevelItem  `protobuf:"bytes,4,opt,name=valueD,proto3" json:"valueD,omitempty"`
	Salts                []*proto1.Salt `protobuf:"bytes,5,rep,name=salts,proto3" json:"salts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *NestedRepeatedDocument) Reset()         { *m = NestedRepeatedDocument{} }
func (m *NestedRepeatedDocument) String() string { return proto.CompactTextString(m) }
func (*NestedRepeatedDocument) ProtoMessage()    {}
func (*NestedRepeatedDocument) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbdf1f37afed577e, []int{18}
}

func (m *NestedRepeatedDocument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NestedRepeatedDocument.Unmarshal(m, b)
}
func (m *NestedRepeatedDocument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NestedRepeatedDocument.Marshal(b, m, deterministic)
}
func (m *NestedRepeatedDocument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NestedRepeatedDocument.Merge(m, src)
}
func (m *NestedRepeatedDocument) XXX_Size() int {
	return xxx_messageInfo_NestedRepeatedDocument.Size(m)
}
func (m *NestedRepeatedDocument) XXX_DiscardUnknown() {
	xxx_messageInfo_NestedRepeatedDocument.DiscardUnknown(m)
}

var xxx_messageInfo_NestedRepeatedDocument proto.InternalMessageInfo

func (m *NestedRepeatedDocument) GetValueA() string {
	if m != nil {
		return m.ValueA
	}
	return ""
}

func (m *NestedRepeatedDocument) GetValueB() string {
	if m != nil {
		return m.ValueB
	}
	return ""
}

func (m *NestedRepeatedDocument) GetValueC() []*SimpleItem {
	if m != nil {
		return m.ValueC
	}
	return nil
}

func (m *NestedRepeatedDocument) GetValueD() *TwoLevelItem {
	if m != nil {
		return m.ValueD
	}
	return nil
}

func (m *NestedRepeatedDocument) GetSalts() []*proto1.Salt {
	if m != nil {
		return m.Salts
	}
	return nil
}

type InvalidHashedFieldDocument struct {
	Value                string         `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Salts                []*proto1.Salt `protobuf:"bytes,2,rep,name=salts,proto3" json:"salts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *InvalidHashedFieldDocument) Reset()         { *m = InvalidHashedFieldDocument{} }
func (m *InvalidHashedFieldDocument) String() string { return proto.CompactTextString(m) }
func (*InvalidHashedFieldDocument) ProtoMessage()    {}
func (*InvalidHashedFieldDocument) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbdf1f37afed577e, []int{19}
}

func (m *InvalidHashedFieldDocument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvalidHashedFieldDocument.Unmarshal(m, b)
}
func (m *InvalidHashedFieldDocument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvalidHashedFieldDocument.Marshal(b, m, deterministic)
}
func (m *InvalidHashedFieldDocument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvalidHashedFieldDocument.Merge(m, src)
}
func (m *InvalidHashedFieldDocument) XXX_Size() int {
	return xxx_messageInfo_InvalidHashedFieldDocument.Size(m)
}
func (m *InvalidHashedFieldDocument) XXX_DiscardUnknown() {
	xxx_messageInfo_InvalidHashedFieldDocument.DiscardUnknown(m)
}

var xxx_messageInfo_InvalidHashedFieldDocument proto.InternalMessageInfo

func (m *InvalidHashedFieldDocument) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *InvalidHashedFieldDocument) GetSalts() []*proto1.Salt {
	if m != nil {
		return m.Salts
	}
	return nil
}

type OneofSample struct {
	ValueA int32 `protobuf:"varint,1,opt,name=valueA,proto3" json:"valueA,omitempty"`
	// Types that are valid to be assigned to OneofBlock:
	//	*OneofSample_ValueB
	//	*OneofSample_ValueC
	//	*OneofSample_ValueD
	OneofBlock           isOneofSample_OneofBlock `protobuf_oneof:"oneofBlock"`
	ValueE               int32                    `protobuf:"varint,5,opt,name=valueE,proto3" json:"valueE,omitempty"`
	Salts                []*proto1.Salt           `protobuf:"bytes,6,rep,name=salts,proto3" json:"salts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *OneofSample) Reset()         { *m = OneofSample{} }
func (m *OneofSample) String() string { return proto.CompactTextString(m) }
func (*OneofSample) ProtoMessage()    {}
func (*OneofSample) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbdf1f37afed577e, []int{20}
}

func (m *OneofSample) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OneofSample.Unmarshal(m, b)
}
func (m *OneofSample) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OneofSample.Marshal(b, m, deterministic)
}
func (m *OneofSample) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OneofSample.Merge(m, src)
}
func (m *OneofSample) XXX_Size() int {
	return xxx_messageInfo_OneofSample.Size(m)
}
func (m *OneofSample) XXX_DiscardUnknown() {
	xxx_messageInfo_OneofSample.DiscardUnknown(m)
}

var xxx_messageInfo_OneofSample proto.InternalMessageInfo

func (m *OneofSample) GetValueA() int32 {
	if m != nil {
		return m.ValueA
	}
	return 0
}

type isOneofSample_OneofBlock interface {
	isOneofSample_OneofBlock()
}

type OneofSample_ValueB struct {
	ValueB int32 `protobuf:"varint,2,opt,name=valueB,proto3,oneof"`
}

type OneofSample_ValueC struct {
	ValueC string `protobuf:"bytes,3,opt,name=valueC,proto3,oneof"`
}

type OneofSample_ValueD struct {
	ValueD *SimpleItem `protobuf:"bytes,4,opt,name=valueD,proto3,oneof"`
}

func (*OneofSample_ValueB) isOneofSample_OneofBlock() {}

func (*OneofSample_ValueC) isOneofSample_OneofBlock() {}

func (*OneofSample_ValueD) isOneofSample_OneofBlock() {}

func (m *OneofSample) GetOneofBlock() isOneofSample_OneofBlock {
	if m != nil {
		return m.OneofBlock
	}
	return nil
}

func (m *OneofSample) GetValueB() int32 {
	if x, ok := m.GetOneofBlock().(*OneofSample_ValueB); ok {
		return x.ValueB
	}
	return 0
}

func (m *OneofSample) GetValueC() string {
	if x, ok := m.GetOneofBlock().(*OneofSample_ValueC); ok {
		return x.ValueC
	}
	return ""
}

func (m *OneofSample) GetValueD() *SimpleItem {
	if x, ok := m.GetOneofBlock().(*OneofSample_ValueD); ok {
		return x.ValueD
	}
	return nil
}

func (m *OneofSample) GetValueE() int32 {
	if m != nil {
		return m.ValueE
	}
	return 0
}

func (m *OneofSample) GetSalts() []*proto1.Salt {
	if m != nil {
		return m.Salts
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*OneofSample) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*OneofSample_ValueB)(nil),
		(*OneofSample_ValueC)(nil),
		(*OneofSample_ValueD)(nil),
	}
}

type LongDocument struct {
	Value0               int64          `protobuf:"varint,16,opt,name=value0,proto3" json:"value0,omitempty"`
	Value1               int64          `protobuf:"varint,1,opt,name=value1,proto3" json:"value1,omitempty"`
	Value2               int64          `protobuf:"varint,2,opt,name=value2,proto3" json:"value2,omitempty"`
	Value3               int64          `protobuf:"varint,3,opt,name=value3,proto3" json:"value3,omitempty"`
	Value4               int64          `protobuf:"varint,4,opt,name=value4,proto3" json:"value4,omitempty"`
	Value5               int64          `protobuf:"varint,5,opt,name=value5,proto3" json:"value5,omitempty"`
	Value6               int64          `protobuf:"varint,6,opt,name=value6,proto3" json:"value6,omitempty"`
	Value7               int64          `protobuf:"varint,7,opt,name=value7,proto3" json:"value7,omitempty"`
	Value8               int64          `protobuf:"varint,8,opt,name=value8,proto3" json:"value8,omitempty"`
	Value9               int64          `protobuf:"varint,9,opt,name=value9,proto3" json:"value9,omitempty"`
	ValueA               int64          `protobuf:"varint,10,opt,name=valueA,proto3" json:"valueA,omitempty"`
	ValueB               int64          `protobuf:"varint,11,opt,name=valueB,proto3" json:"valueB,omitempty"`
	ValueC               int64          `protobuf:"varint,12,opt,name=valueC,proto3" json:"valueC,omitempty"`
	ValueD               int64          `protobuf:"varint,13,opt,name=valueD,proto3" json:"valueD,omitempty"`
	ValueE               int64          `protobuf:"varint,14,opt,name=valueE,proto3" json:"valueE,omitempty"`
	Salts                []*proto1.Salt `protobuf:"bytes,15,rep,name=salts,proto3" json:"salts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *LongDocument) Reset()         { *m = LongDocument{} }
func (m *LongDocument) String() string { return proto.CompactTextString(m) }
func (*LongDocument) ProtoMessage()    {}
func (*LongDocument) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbdf1f37afed577e, []int{21}
}

func (m *LongDocument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LongDocument.Unmarshal(m, b)
}
func (m *LongDocument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LongDocument.Marshal(b, m, deterministic)
}
func (m *LongDocument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LongDocument.Merge(m, src)
}
func (m *LongDocument) XXX_Size() int {
	return xxx_messageInfo_LongDocument.Size(m)
}
func (m *LongDocument) XXX_DiscardUnknown() {
	xxx_messageInfo_LongDocument.DiscardUnknown(m)
}

var xxx_messageInfo_LongDocument proto.InternalMessageInfo

func (m *LongDocument) GetValue0() int64 {
	if m != nil {
		return m.Value0
	}
	return 0
}

func (m *LongDocument) GetValue1() int64 {
	if m != nil {
		return m.Value1
	}
	return 0
}

func (m *LongDocument) GetValue2() int64 {
	if m != nil {
		return m.Value2
	}
	return 0
}

func (m *LongDocument) GetValue3() int64 {
	if m != nil {
		return m.Value3
	}
	return 0
}

func (m *LongDocument) GetValue4() int64 {
	if m != nil {
		return m.Value4
	}
	return 0
}

func (m *LongDocument) GetValue5() int64 {
	if m != nil {
		return m.Value5
	}
	return 0
}

func (m *LongDocument) GetValue6() int64 {
	if m != nil {
		return m.Value6
	}
	return 0
}

func (m *LongDocument) GetValue7() int64 {
	if m != nil {
		return m.Value7
	}
	return 0
}

func (m *LongDocument) GetValue8() int64 {
	if m != nil {
		return m.Value8
	}
	return 0
}

func (m *LongDocument) GetValue9() int64 {
	if m != nil {
		return m.Value9
	}
	return 0
}

func (m *LongDocument) GetValueA() int64 {
	if m != nil {
		return m.ValueA
	}
	return 0
}

func (m *LongDocument) GetValueB() int64 {
	if m != nil {
		return m.ValueB
	}
	return 0
}

func (m *LongDocument) GetValueC() int64 {
	if m != nil {
		return m.ValueC
	}
	return 0
}

func (m *LongDocument) GetValueD() int64 {
	if m != nil {
		return m.ValueD
	}
	return 0
}

func (m *LongDocument) GetValueE() int64 {
	if m != nil {
		return m.ValueE
	}
	return 0
}

func (m *LongDocument) GetSalts() []*proto1.Salt {
	if m != nil {
		return m.Salts
	}
	return nil
}

type Integers struct {
	ValueA               int32          `protobuf:"varint,1,opt,name=valueA,proto3" json:"valueA,omitempty"`
	ValueB               int64          `protobuf:"varint,2,opt,name=valueB,proto3" json:"valueB,omitempty"`
	ValueC               uint32         `protobuf:"varint,3,opt,name=valueC,proto3" json:"valueC,omitempty"`
	ValueD               uint64         `protobuf:"varint,4,opt,name=valueD,proto3" json:"valueD,omitempty"`
	ValueE               int32          `protobuf:"zigzag32,5,opt,name=valueE,proto3" json:"valueE,omitempty"`
	ValueF               int64          `protobuf:"zigzag64,6,opt,name=valueF,proto3" json:"valueF,omitempty"`
	ValueG               uint32         `protobuf:"fixed32,7,opt,name=valueG,proto3" json:"valueG,omitempty"`
	ValueH               uint64         `protobuf:"fixed64,8,opt,name=valueH,proto3" json:"valueH,omitempty"`
	ValueI               int32          `protobuf:"fixed32,9,opt,name=valueI,proto3" json:"valueI,omitempty"`
	ValueJ               int64          `protobuf:"fixed64,10,opt,name=valueJ,proto3" json:"valueJ,omitempty"`
	Salts                []*proto1.Salt `protobuf:"bytes,11,rep,name=salts,proto3" json:"salts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Integers) Reset()         { *m = Integers{} }
func (m *Integers) String() string { return proto.CompactTextString(m) }
func (*Integers) ProtoMessage()    {}
func (*Integers) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbdf1f37afed577e, []int{22}
}

func (m *Integers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Integers.Unmarshal(m, b)
}
func (m *Integers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Integers.Marshal(b, m, deterministic)
}
func (m *Integers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Integers.Merge(m, src)
}
func (m *Integers) XXX_Size() int {
	return xxx_messageInfo_Integers.Size(m)
}
func (m *Integers) XXX_DiscardUnknown() {
	xxx_messageInfo_Integers.DiscardUnknown(m)
}

var xxx_messageInfo_Integers proto.InternalMessageInfo

func (m *Integers) GetValueA() int32 {
	if m != nil {
		return m.ValueA
	}
	return 0
}

func (m *Integers) GetValueB() int64 {
	if m != nil {
		return m.ValueB
	}
	return 0
}

func (m *Integers) GetValueC() uint32 {
	if m != nil {
		return m.ValueC
	}
	return 0
}

func (m *Integers) GetValueD() uint64 {
	if m != nil {
		return m.ValueD
	}
	return 0
}

func (m *Integers) GetValueE() int32 {
	if m != nil {
		return m.ValueE
	}
	return 0
}

func (m *Integers) GetValueF() int64 {
	if m != nil {
		return m.ValueF
	}
	return 0
}

func (m *Integers) GetValueG() uint32 {
	if m != nil {
		return m.ValueG
	}
	return 0
}

func (m *Integers) GetValueH() uint64 {
	if m != nil {
		return m.ValueH
	}
	return 0
}

func (m *Integers) GetValueI() int32 {
	if m != nil {
		return m.ValueI
	}
	return 0
}

func (m *Integers) GetValueJ() int64 {
	if m != nil {
		return m.ValueJ
	}
	return 0
}

func (m *Integers) GetSalts() []*proto1.Salt {
	if m != nil {
		return m.Salts
	}
	return nil
}

type ContainSalts struct {
	ValueA               string         `protobuf:"bytes,1,opt,name=valueA,proto3" json:"valueA,omitempty"`
	ValueB               int32          `protobuf:"varint,2,opt,name=valueB,proto3" json:"valueB,omitempty"`
	Salts                []*proto1.Salt `protobuf:"bytes,3,rep,name=salts,proto3" json:"salts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ContainSalts) Reset()         { *m = ContainSalts{} }
func (m *ContainSalts) String() string { return proto.CompactTextString(m) }
func (*ContainSalts) ProtoMessage()    {}
func (*ContainSalts) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbdf1f37afed577e, []int{23}
}

func (m *ContainSalts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainSalts.Unmarshal(m, b)
}
func (m *ContainSalts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainSalts.Marshal(b, m, deterministic)
}
func (m *ContainSalts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainSalts.Merge(m, src)
}
func (m *ContainSalts) XXX_Size() int {
	return xxx_messageInfo_ContainSalts.Size(m)
}
func (m *ContainSalts) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainSalts.DiscardUnknown(m)
}

var xxx_messageInfo_ContainSalts proto.InternalMessageInfo

func (m *ContainSalts) GetValueA() string {
	if m != nil {
		return m.ValueA
	}
	return ""
}

func (m *ContainSalts) GetValueB() int32 {
	if m != nil {
		return m.ValueB
	}
	return 0
}

func (m *ContainSalts) GetSalts() []*proto1.Salt {
	if m != nil {
		return m.Salts
	}
	return nil
}

type ExampleWithoutSalts struct {
	ValueA               string   `protobuf:"bytes,1,opt,name=valueA,proto3" json:"valueA,omitempty"`
	ValueB               int32    `protobuf:"varint,2,opt,name=valueB,proto3" json:"valueB,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExampleWithoutSalts) Reset()         { *m = ExampleWithoutSalts{} }
func (m *ExampleWithoutSalts) String() string { return proto.CompactTextString(m) }
func (*ExampleWithoutSalts) ProtoMessage()    {}
func (*ExampleWithoutSalts) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbdf1f37afed577e, []int{24}
}

func (m *ExampleWithoutSalts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExampleWithoutSalts.Unmarshal(m, b)
}
func (m *ExampleWithoutSalts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExampleWithoutSalts.Marshal(b, m, deterministic)
}
func (m *ExampleWithoutSalts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExampleWithoutSalts.Merge(m, src)
}
func (m *ExampleWithoutSalts) XXX_Size() int {
	return xxx_messageInfo_ExampleWithoutSalts.Size(m)
}
func (m *ExampleWithoutSalts) XXX_DiscardUnknown() {
	xxx_messageInfo_ExampleWithoutSalts.DiscardUnknown(m)
}

var xxx_messageInfo_ExampleWithoutSalts proto.InternalMessageInfo

func (m *ExampleWithoutSalts) GetValueA() string {
	if m != nil {
		return m.ValueA
	}
	return ""
}

func (m *ExampleWithoutSalts) GetValueB() int32 {
	if m != nil {
		return m.ValueB
	}
	return 0
}

type Name struct {
	First                string   `protobuf:"bytes,1,opt,name=first,proto3" json:"first,omitempty"`
	Last                 string   `protobuf:"bytes,2,opt,name=last,proto3" json:"last,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Name) Reset()         { *m = Name{} }
func (m *Name) String() string { return proto.CompactTextString(m) }
func (*Name) ProtoMessage()    {}
func (*Name) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbdf1f37afed577e, []int{25}
}

func (m *Name) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Name.Unmarshal(m, b)
}
func (m *Name) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Name.Marshal(b, m, deterministic)
}
func (m *Name) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Name.Merge(m, src)
}
func (m *Name) XXX_Size() int {
	return xxx_messageInfo_Name.Size(m)
}
func (m *Name) XXX_DiscardUnknown() {
	xxx_messageInfo_Name.DiscardUnknown(m)
}

var xxx_messageInfo_Name proto.InternalMessageInfo

func (m *Name) GetFirst() string {
	if m != nil {
		return m.First
	}
	return ""
}

func (m *Name) GetLast() string {
	if m != nil {
		return m.Last
	}
	return ""
}

type PhoneNumber struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Countrycode          string   `protobuf:"bytes,2,opt,name=countrycode,proto3" json:"countrycode,omitempty"`
	Number               string   `protobuf:"bytes,3,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PhoneNumber) Reset()         { *m = PhoneNumber{} }
func (m *PhoneNumber) String() string { return proto.CompactTextString(m) }
func (*PhoneNumber) ProtoMessage()    {}
func (*PhoneNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbdf1f37afed577e, []int{26}
}

func (m *PhoneNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhoneNumber.Unmarshal(m, b)
}
func (m *PhoneNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhoneNumber.Marshal(b, m, deterministic)
}
func (m *PhoneNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhoneNumber.Merge(m, src)
}
func (m *PhoneNumber) XXX_Size() int {
	return xxx_messageInfo_PhoneNumber.Size(m)
}
func (m *PhoneNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_PhoneNumber.DiscardUnknown(m)
}

var xxx_messageInfo_PhoneNumber proto.InternalMessageInfo

func (m *PhoneNumber) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *PhoneNumber) GetCountrycode() string {
	if m != nil {
		return m.Countrycode
	}
	return ""
}

func (m *PhoneNumber) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

type ExampleNested struct {
	HashedValue          []byte   `protobuf:"bytes,1,opt,name=hashed_value,json=hashedValue,proto3" json:"hashed_value,omitempty"`
	Name                 *Name    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExampleNested) Reset()         { *m = ExampleNested{} }
func (m *ExampleNested) String() string { return proto.CompactTextString(m) }
func (*ExampleNested) ProtoMessage()    {}
func (*ExampleNested) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbdf1f37afed577e, []int{27}
}

func (m *ExampleNested) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExampleNested.Unmarshal(m, b)
}
func (m *ExampleNested) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExampleNested.Marshal(b, m, deterministic)
}
func (m *ExampleNested) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExampleNested.Merge(m, src)
}
func (m *ExampleNested) XXX_Size() int {
	return xxx_messageInfo_ExampleNested.Size(m)
}
func (m *ExampleNested) XXX_DiscardUnknown() {
	xxx_messageInfo_ExampleNested.DiscardUnknown(m)
}

var xxx_messageInfo_ExampleNested proto.InternalMessageInfo

func (m *ExampleNested) GetHashedValue() []byte {
	if m != nil {
		return m.HashedValue
	}
	return nil
}

func (m *ExampleNested) GetName() *Name {
	if m != nil {
		return m.Name
	}
	return nil
}

type AppendFieldDocument struct {
	Name                 *Name          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Names                []*Name        `protobuf:"bytes,2,rep,name=names,proto3" json:"names,omitempty"`
	PhoneNumbers         []*PhoneNumber `protobuf:"bytes,3,rep,name=phone_numbers,json=phoneNumbers,proto3" json:"phone_numbers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AppendFieldDocument) Reset()         { *m = AppendFieldDocument{} }
func (m *AppendFieldDocument) String() string { return proto.CompactTextString(m) }
func (*AppendFieldDocument) ProtoMessage()    {}
func (*AppendFieldDocument) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbdf1f37afed577e, []int{28}
}

func (m *AppendFieldDocument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendFieldDocument.Unmarshal(m, b)
}
func (m *AppendFieldDocument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendFieldDocument.Marshal(b, m, deterministic)
}
func (m *AppendFieldDocument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendFieldDocument.Merge(m, src)
}
func (m *AppendFieldDocument) XXX_Size() int {
	return xxx_messageInfo_AppendFieldDocument.Size(m)
}
func (m *AppendFieldDocument) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendFieldDocument.DiscardUnknown(m)
}

var xxx_messageInfo_AppendFieldDocument proto.InternalMessageInfo

func (m *AppendFieldDocument) GetName() *Name {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *AppendFieldDocument) GetNames() []*Name {
	if m != nil {
		return m.Names
	}
	return nil
}

func (m *AppendFieldDocument) GetPhoneNumbers() []*PhoneNumber {
	if m != nil {
		return m.PhoneNumbers
	}
	return nil
}

type UnsupportedAppendDocument struct {
	Name                 *Name          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Nested               *ExampleNested `protobuf:"bytes,2,opt,name=nested,proto3" json:"nested,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UnsupportedAppendDocument) Reset()         { *m = UnsupportedAppendDocument{} }
func (m *UnsupportedAppendDocument) String() string { return proto.CompactTextString(m) }
func (*UnsupportedAppendDocument) ProtoMessage()    {}
func (*UnsupportedAppendDocument) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbdf1f37afed577e, []int{29}
}

func (m *UnsupportedAppendDocument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnsupportedAppendDocument.Unmarshal(m, b)
}
func (m *UnsupportedAppendDocument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnsupportedAppendDocument.Marshal(b, m, deterministic)
}
func (m *UnsupportedAppendDocument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnsupportedAppendDocument.Merge(m, src)
}
func (m *UnsupportedAppendDocument) XXX_Size() int {
	return xxx_messageInfo_UnsupportedAppendDocument.Size(m)
}
func (m *UnsupportedAppendDocument) XXX_DiscardUnknown() {
	xxx_messageInfo_UnsupportedAppendDocument.DiscardUnknown(m)
}

var xxx_messageInfo_UnsupportedAppendDocument proto.InternalMessageInfo

func (m *UnsupportedAppendDocument) GetName() *Name {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *UnsupportedAppendDocument) GetNested() *ExampleNested {
	if m != nil {
		return m.Nested
	}
	return nil
}

type NoSaltDocument struct {
	ValueNoSalt          string   `protobuf:"bytes,1,opt,name=valueNoSalt,proto3" json:"valueNoSalt,omitempty"`
	ValueSalt            string   `protobuf:"bytes,2,opt,name=valueSalt,proto3" json:"valueSalt,omitempty"`
	Name                 *Name    `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoSaltDocument) Reset()         { *m = NoSaltDocument{} }
func (m *NoSaltDocument) String() string { return proto.CompactTextString(m) }
func (*NoSaltDocument) ProtoMessage()    {}
func (*NoSaltDocument) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbdf1f37afed577e, []int{30}
}

func (m *NoSaltDocument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoSaltDocument.Unmarshal(m, b)
}
func (m *NoSaltDocument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoSaltDocument.Marshal(b, m, deterministic)
}
func (m *NoSaltDocument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoSaltDocument.Merge(m, src)
}
func (m *NoSaltDocument) XXX_Size() int {
	return xxx_messageInfo_NoSaltDocument.Size(m)
}
func (m *NoSaltDocument) XXX_DiscardUnknown() {
	xxx_messageInfo_NoSaltDocument.DiscardUnknown(m)
}

var xxx_messageInfo_NoSaltDocument proto.InternalMessageInfo

func (m *NoSaltDocument) GetValueNoSalt() string {
	if m != nil {
		return m.ValueNoSalt
	}
	return ""
}

func (m *NoSaltDocument) GetValueSalt() string {
	if m != nil {
		return m.ValueSalt
	}
	return ""
}

func (m *NoSaltDocument) GetName() *Name {
	if m != nil {
		return m.Name
	}
	return nil
}

type ExampleWithPaddingField struct {
	ValueA               string         `protobuf:"bytes,1,opt,name=valueA,proto3" json:"valueA,omitempty"`
	ValueB               []byte         `protobuf:"bytes,2,opt,name=valueB,proto3" json:"valueB,omitempty"`
	Salts                []*proto1.Salt `protobuf:"bytes,3,rep,name=salts,proto3" json:"salts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ExampleWithPaddingField) Reset()         { *m = ExampleWithPaddingField{} }
func (m *ExampleWithPaddingField) String() string { return proto.CompactTextString(m) }
func (*ExampleWithPaddingField) ProtoMessage()    {}
func (*ExampleWithPaddingField) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbdf1f37afed577e, []int{31}
}

func (m *ExampleWithPaddingField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExampleWithPaddingField.Unmarshal(m, b)
}
func (m *ExampleWithPaddingField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExampleWithPaddingField.Marshal(b, m, deterministic)
}
func (m *ExampleWithPaddingField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExampleWithPaddingField.Merge(m, src)
}
func (m *ExampleWithPaddingField) XXX_Size() int {
	return xxx_messageInfo_ExampleWithPaddingField.Size(m)
}
func (m *ExampleWithPaddingField) XXX_DiscardUnknown() {
	xxx_messageInfo_ExampleWithPaddingField.DiscardUnknown(m)
}

var xxx_messageInfo_ExampleWithPaddingField proto.InternalMessageInfo

func (m *ExampleWithPaddingField) GetValueA() string {
	if m != nil {
		return m.ValueA
	}
	return ""
}

func (m *ExampleWithPaddingField) GetValueB() []byte {
	if m != nil {
		return m.ValueB
	}
	return nil
}

func (m *ExampleWithPaddingField) GetSalts() []*proto1.Salt {
	if m != nil {
		return m.Salts
	}
	return nil
}

type NamePadded struct {
	First                string   `protobuf:"bytes,1,opt,name=first,proto3" json:"first,omitempty"`
	Last                 string   `protobuf:"bytes,2,opt,name=last,proto3" json:"last,omitempty"`
	Age                  int32    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NamePadded) Reset()         { *m = NamePadded{} }
func (m *NamePadded) String() string { return proto.CompactTextString(m) }
func (*NamePadded) ProtoMessage()    {}
func (*NamePadded) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbdf1f37afed577e, []int{32}
}

func (m *NamePadded) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamePadded.Unmarshal(m, b)
}
func (m *NamePadded) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamePadded.Marshal(b, m, deterministic)
}
func (m *NamePadded) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamePadded.Merge(m, src)
}
func (m *NamePadded) XXX_Size() int {
	return xxx_messageInfo_NamePadded.Size(m)
}
func (m *NamePadded) XXX_DiscardUnknown() {
	xxx_messageInfo_NamePadded.DiscardUnknown(m)
}

var xxx_messageInfo_NamePadded proto.InternalMessageInfo

func (m *NamePadded) GetFirst() string {
	if m != nil {
		return m.First
	}
	return ""
}

func (m *NamePadded) GetLast() string {
	if m != nil {
		return m.Last
	}
	return ""
}

func (m *NamePadded) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

type AppendFieldPaddingDocument struct {
	Names                []*NamePadded `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *AppendFieldPaddingDocument) Reset()         { *m = AppendFieldPaddingDocument{} }
func (m *AppendFieldPaddingDocument) String() string { return proto.CompactTextString(m) }
func (*AppendFieldPaddingDocument) ProtoMessage()    {}
func (*AppendFieldPaddingDocument) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbdf1f37afed577e, []int{33}
}

func (m *AppendFieldPaddingDocument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendFieldPaddingDocument.Unmarshal(m, b)
}
func (m *AppendFieldPaddingDocument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendFieldPaddingDocument.Marshal(b, m, deterministic)
}
func (m *AppendFieldPaddingDocument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendFieldPaddingDocument.Merge(m, src)
}
func (m *AppendFieldPaddingDocument) XXX_Size() int {
	return xxx_messageInfo_AppendFieldPaddingDocument.Size(m)
}
func (m *AppendFieldPaddingDocument) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendFieldPaddingDocument.DiscardUnknown(m)
}

var xxx_messageInfo_AppendFieldPaddingDocument proto.InternalMessageInfo

func (m *AppendFieldPaddingDocument) GetNames() []*NamePadded {
	if m != nil {
		return m.Names
	}
	return nil
}

func init() {
	proto.RegisterEnum("documents.Enum", Enum_name, Enum_value)
	proto.RegisterType((*ExampleDocument)(nil), "documents.ExampleDocument")
	proto.RegisterType((*AllFieldTypes)(nil), "documents.AllFieldTypes")
	proto.RegisterType((*AllFieldTypesSalts)(nil), "documents.AllFieldTypesSalts")
	proto.RegisterType((*SimpleItem)(nil), "documents.SimpleItem")
	proto.RegisterType((*RepeatedItem)(nil), "documents.RepeatedItem")
	proto.RegisterType((*SimpleMap)(nil), "documents.SimpleMap")
	proto.RegisterMapType((map[int32]string)(nil), "documents.SimpleMap.ValueEntry")
	proto.RegisterType((*SimpleStringMap)(nil), "documents.SimpleStringMap")
	proto.RegisterMapType((map[string]string)(nil), "documents.SimpleStringMap.ValueEntry")
	proto.RegisterType((*NestedMap)(nil), "documents.NestedMap")
	proto.RegisterMapType((map[int32]*SimpleMap)(nil), "documents.NestedMap.ValueEntry")
	proto.RegisterType((*SimpleEntry)(nil), "documents.SimpleEntry")
	proto.RegisterType((*SimpleEntries)(nil), "documents.SimpleEntries")
	proto.RegisterType((*Entry)(nil), "documents.Entry")
	proto.RegisterType((*Entries)(nil), "documents.Entries")
	proto.RegisterType((*BytesKeyEntry)(nil), "documents.BytesKeyEntry")
	proto.RegisterType((*BytesKeyEntries)(nil), "documents.BytesKeyEntries")
	proto.RegisterType((*TwoLevelRepeatedDocument)(nil), "documents.TwoLevelRepeatedDocument")
	proto.RegisterType((*SimpleRepeatedDocument)(nil), "documents.SimpleRepeatedDocument")
	proto.RegisterType((*SimpleMapDocument)(nil), "documents.SimpleMapDocument")
	proto.RegisterMapType((map[string]string)(nil), "documents.SimpleMapDocument.ValueCEntry")
	proto.RegisterMapType((map[int32]string)(nil), "documents.SimpleMapDocument.ValueDEntry")
	proto.RegisterType((*TwoLevelItem)(nil), "documents.TwoLevelItem")
	proto.RegisterType((*NestedRepeatedDocument)(nil), "documents.NestedRepeatedDocument")
	proto.RegisterType((*InvalidHashedFieldDocument)(nil), "documents.InvalidHashedFieldDocument")
	proto.RegisterType((*OneofSample)(nil), "documents.oneofSample")
	proto.RegisterType((*LongDocument)(nil), "documents.LongDocument")
	proto.RegisterType((*Integers)(nil), "documents.Integers")
	proto.RegisterType((*ContainSalts)(nil), "documents.ContainSalts")
	proto.RegisterType((*ExampleWithoutSalts)(nil), "documents.ExampleWithoutSalts")
	proto.RegisterType((*Name)(nil), "documents.Name")
	proto.RegisterType((*PhoneNumber)(nil), "documents.PhoneNumber")
	proto.RegisterType((*ExampleNested)(nil), "documents.ExampleNested")
	proto.RegisterType((*AppendFieldDocument)(nil), "documents.AppendFieldDocument")
	proto.RegisterType((*UnsupportedAppendDocument)(nil), "documents.UnsupportedAppendDocument")
	proto.RegisterType((*NoSaltDocument)(nil), "documents.NoSaltDocument")
	proto.RegisterType((*ExampleWithPaddingField)(nil), "documents.ExampleWithPaddingField")
	proto.RegisterType((*NamePadded)(nil), "documents.NamePadded")
	proto.RegisterType((*AppendFieldPaddingDocument)(nil), "documents.AppendFieldPaddingDocument")
}

func init() { proto.RegisterFile("examples/documents/example.proto", fileDescriptor_bbdf1f37afed577e) }

var fileDescriptor_bbdf1f37afed577e = []byte{
	// 1662 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0x4b, 0x6f, 0xdb, 0xc6,
	0x16, 0x0e, 0xf5, 0xb0, 0xad, 0x43, 0xca, 0x92, 0x99, 0x5c, 0x87, 0x71, 0xee, 0x45, 0x14, 0xde,
	0x16, 0x15, 0x8c, 0x44, 0x8e, 0x95, 0x97, 0xd3, 0x4d, 0x6a, 0x3d, 0x12, 0x3b, 0x0f, 0xc3, 0xa0,
	0xd3, 0x14, 0x68, 0xd1, 0x0a, 0xb4, 0x39, 0x96, 0x85, 0x50, 0x1c, 0x42, 0xa4, 0x92, 0xaa, 0xcd,
	0xa2, 0x40, 0x5b, 0xf4, 0x3f, 0x14, 0x45, 0xd1, 0x65, 0x97, 0x01, 0x0a, 0x74, 0xd1, 0x55, 0xbd,
	0xcb, 0xa2, 0xcb, 0xfe, 0x88, 0xfe, 0x81, 0xec, 0x8b, 0x99, 0xe1, 0x0c, 0x87, 0x96, 0x58, 0xcb,
	0x6e, 0xbb, 0x92, 0xf8, 0xcd, 0x99, 0x33, 0xdf, 0x79, 0xcc, 0x99, 0x39, 0x03, 0x15, 0xf4, 0xa9,
	0xdd, 0xf7, 0x5d, 0x14, 0xac, 0x38, 0x78, 0x6f, 0xd8, 0x47, 0x5e, 0x18, 0xac, 0x44, 0x50, 0xcd,
	0x1f, 0xe0, 0x10, 0xeb, 0x05, 0x31, 0xb0, 0x74, 0xa9, 0x8b, 0x71, 0xd7, 0x45, 0x2b, 0x74, 0x60,
	0x77, 0xb8, 0xbf, 0x12, 0xf6, 0xfa, 0x28, 0x08, 0xed, 0xbe, 0xcf, 0x64, 0x97, 0x0c, 0x7f, 0x80,
	0xf1, 0x7e, 0xc0, 0x04, 0x56, 0xe8, 0x47, 0x34, 0x72, 0x3e, 0x31, 0x12, 0xd8, 0x6e, 0xc8, 0x06,
	0xcc, 0x57, 0x39, 0x28, 0xb5, 0xd9, 0x82, 0xad, 0x68, 0x21, 0x7d, 0x11, 0x66, 0x9e, 0xdb, 0xee,
	0x10, 0xad, 0x1b, 0x4a, 0x45, 0xa9, 0x16, 0xac, 0xe8, 0x4b, 0xe0, 0x0d, 0x23, 0x23, 0xe1, 0x0d,
	0x81, 0xaf, 0x1a, 0xd9, 0x8a, 0x52, 0xcd, 0x46, 0xf8, 0xaa, 0xc0, 0xeb, 0x46, 0x4e, 0xc2, 0xeb,
	0xfa, 0x65, 0xd0, 0xe8, 0xbf, 0xce, 0xee, 0x28, 0x44, 0xc1, 0xaa, 0x91, 0xaf, 0x28, 0x55, 0xcd,
	0x52, 0x99, 0x36, 0x0a, 0xe9, 0x55, 0x28, 0x3d, 0x25, 0x9f, 0x4d, 0xbb, 0x8f, 0xdc, 0xa6, 0x1d,
	0x20, 0xc7, 0x98, 0xa1, 0x52, 0x47, 0x61, 0x7d, 0x15, 0x16, 0x98, 0x32, 0x0f, 0x87, 0x9d, 0x5e,
	0xd7, 0xc3, 0x03, 0xe4, 0x18, 0xb3, 0x44, 0xb6, 0x91, 0xff, 0xe1, 0xf0, 0x0d, 0x9c, 0xb1, 0x4a,
	0x74, 0x7c, 0x0b, 0x87, 0x9b, 0x6c, 0x54, 0x5f, 0x86, 0x22, 0x9b, 0xc2, 0xc5, 0xe7, 0x62, 0x71,
	0xc5, 0x62, 0xdc, 0xb8, 0xec, 0x0a, 0x94, 0x63, 0xf5, 0x07, 0x76, 0x70, 0x80, 0x1c, 0xa3, 0xc0,
	0xc4, 0x7f, 0xa4, 0xe2, 0xf3, 0x5c, 0xfb, 0x06, 0x1d, 0xd4, 0xaf, 0x40, 0x01, 0x79, 0xc3, 0x7e,
	0x27, 0x1c, 0xf9, 0xc8, 0x80, 0x8a, 0x52, 0x9d, 0xaf, 0x97, 0x6a, 0x22, 0x86, 0xb5, 0xb6, 0x37,
	0xec, 0x5b, 0x73, 0x44, 0xe2, 0xc9, 0xc8, 0x47, 0xfa, 0x7f, 0xa1, 0xc0, 0xcc, 0xc6, 0xd8, 0x35,
	0xb4, 0x8a, 0x52, 0x9d, 0xb3, 0x62, 0x40, 0x5f, 0x86, 0x9c, 0x67, 0xf7, 0x91, 0x51, 0xac, 0x28,
	0x55, 0x35, 0xa1, 0x66, 0xcb, 0xee, 0xa3, 0x46, 0xfe, 0x57, 0xca, 0x80, 0xca, 0xe8, 0x97, 0x61,
	0xce, 0xb7, 0x1d, 0xa7, 0xe7, 0x75, 0xd7, 0x8d, 0x79, 0x12, 0x9e, 0x46, 0xfe, 0xd5, 0xe1, 0x1b,
	0xa8, 0x58, 0x02, 0x96, 0x44, 0x1a, 0x46, 0x89, 0xd9, 0x90, 0x14, 0x69, 0xe8, 0x26, 0xe4, 0x49,
	0x72, 0x04, 0x86, 0x5a, 0xc9, 0x56, 0xd5, 0xba, 0x56, 0x63, 0x79, 0x53, 0xdb, 0xb1, 0xdd, 0xd0,
	0x62, 0x43, 0xe6, 0x77, 0x0a, 0x14, 0xd7, 0x5d, 0xf7, 0x5e, 0x0f, 0xb9, 0x0e, 0x31, 0x22, 0x20,
	0x01, 0x0d, 0xc2, 0x41, 0xcf, 0xeb, 0x76, 0x28, 0xf7, 0x28, 0x6d, 0x54, 0x86, 0xd1, 0x80, 0xe9,
	0x2d, 0x28, 0x93, 0x6c, 0xed, 0xd0, 0x74, 0x8d, 0xc4, 0x32, 0xd4, 0xac, 0xa5, 0x1a, 0x4b, 0xeb,
	0x1a, 0x4f, 0xeb, 0xda, 0x13, 0x9e, 0xd6, 0xd6, 0x3c, 0x99, 0xb3, 0x43, 0xfe, 0x32, 0x2d, 0x82,
	0x5e, 0x36, 0x9d, 0xde, 0xd7, 0x0a, 0xe8, 0x09, 0x7a, 0x64, 0x70, 0x32, 0x47, 0x2d, 0xc9, 0xb1,
	0x9a, 0xc2, 0x51, 0x3b, 0x15, 0x8f, 0xb7, 0x00, 0x76, 0x7a, 0x64, 0x5f, 0x6d, 0x86, 0xa8, 0x9f,
	0xb6, 0xa7, 0xcc, 0x11, 0x68, 0x16, 0xf2, 0x91, 0x1d, 0x22, 0x87, 0xca, 0x5d, 0x95, 0xe4, 0x88,
	0xea, 0xff, 0x48, 0x41, 0x8f, 0xd5, 0x1d, 0xbb, 0x25, 0xa7, 0x21, 0xf8, 0x12, 0x0a, 0x4c, 0xe3,
	0x63, 0xdb, 0xd7, 0x6f, 0x42, 0x9e, 0xfb, 0x85, 0x4c, 0xb8, 0x34, 0xb6, 0xec, 0x63, 0xdb, 0xaf,
	0x51, 0xe3, 0xdb, 0x5e, 0x38, 0x18, 0x59, 0x4c, 0x7a, 0x69, 0x0d, 0x20, 0x06, 0xf5, 0x32, 0x64,
	0x9f, 0xa1, 0x11, 0xb5, 0x30, 0x6f, 0x91, 0xbf, 0xfa, 0x39, 0xae, 0x96, 0xd1, 0x63, 0x1f, 0xef,
	0x66, 0xd6, 0x14, 0xf3, 0x27, 0x05, 0x4a, 0x4c, 0xf3, 0x0e, 0x0d, 0x01, 0x21, 0xd1, 0x48, 0x92,
	0x78, 0x7b, 0x8c, 0x84, 0x10, 0x95, 0xa8, 0xf0, 0x24, 0x66, 0x53, 0x63, 0xcb, 0x33, 0xa9, 0x96,
	0xa7, 0xb3, 0x2e, 0x1c, 0xc7, 0xfa, 0x67, 0x05, 0x0a, 0x5b, 0x28, 0x08, 0x91, 0x73, 0x8c, 0xd3,
	0x84, 0xd0, 0xb8, 0xd3, 0xa6, 0xa2, 0xb8, 0x75, 0x8c, 0x63, 0x97, 0x65, 0x8a, 0x6a, 0xfd, 0xdc,
	0xa4, 0x78, 0xc9, 0xc4, 0x1f, 0x82, 0xca, 0x70, 0xa6, 0xf0, 0x22, 0xa9, 0x52, 0xe1, 0x60, 0xd4,
	0x89, 0x2d, 0x9f, 0xa3, 0xc0, 0x43, 0x34, 0xd2, 0x2f, 0x81, 0xca, 0x06, 0x65, 0x27, 0x00, 0x85,
	0x28, 0x27, 0xf3, 0x33, 0x28, 0xc6, 0xca, 0x7a, 0x28, 0xd0, 0xdb, 0x30, 0x8b, 0xd8, 0xdf, 0xc8,
	0x15, 0x8b, 0x63, 0x7c, 0x58, 0xac, 0xce, 0xd2, 0x58, 0xfd, 0x72, 0xf8, 0x46, 0x5a, 0xdf, 0xe2,
	0x73, 0xa7, 0x71, 0x8c, 0xe9, 0x42, 0x7e, 0x0a, 0x13, 0xe2, 0xed, 0x96, 0x49, 0x39, 0xc2, 0xb2,
	0x74, 0x63, 0x1f, 0x3d, 0xc2, 0x9a, 0x89, 0xa3, 0xaa, 0x69, 0x7a, 0x30, 0xcb, 0x6d, 0xbc, 0x7b,
	0xd4, 0xc6, 0x72, 0xa2, 0xac, 0xff, 0x33, 0xd6, 0xdd, 0x85, 0x22, 0x3d, 0x01, 0x1f, 0xa2, 0x11,
	0xb3, 0xd2, 0x80, 0x59, 0xdb, 0x71, 0x06, 0x28, 0x08, 0xa2, 0x8a, 0xc5, 0x3f, 0x27, 0x27, 0xa9,
	0xf9, 0x12, 0x4a, 0xb2, 0x82, 0x89, 0xc1, 0x31, 0x24, 0xe2, 0x89, 0xd5, 0x1a, 0x0b, 0xc4, 0x80,
	0x73, 0xc4, 0x00, 0xbe, 0xcc, 0xc9, 0xe8, 0x7f, 0xa3, 0x80, 0xf1, 0xe4, 0x05, 0x7e, 0x84, 0x9e,
	0x23, 0x97, 0x97, 0xb5, 0x63, 0xaf, 0x15, 0x2b, 0x52, 0x0d, 0x23, 0x9a, 0xcf, 0x4b, 0xf4, 0xe4,
	0xda, 0x78, 0xa2, 0xe2, 0xf6, 0x95, 0x02, 0x8b, 0x2c, 0xf1, 0xa6, 0xe6, 0x71, 0xdc, 0xf5, 0xa6,
	0x49, 0xd7, 0xe3, 0x78, 0x33, 0xa6, 0x91, 0x4b, 0xa7, 0xf1, 0x47, 0x06, 0x16, 0xc4, 0x7e, 0x3c,
	0x35, 0x83, 0xfb, 0x09, 0x06, 0x6a, 0xbd, 0x3a, 0x69, 0xb7, 0x73, 0xed, 0xac, 0xe0, 0x34, 0x13,
	0xb5, 0x91, 0x53, 0x7e, 0x2f, 0x52, 0xd4, 0x8a, 0x38, 0x4f, 0xa1, 0xa8, 0xc5, 0x4a, 0x57, 0x34,
	0x2f, 0x36, 0x3a, 0x9f, 0x5e, 0xbb, 0xee, 0x80, 0x2a, 0x71, 0x38, 0x49, 0x7d, 0x15, 0x53, 0x5b,
	0x27, 0x3f, 0x50, 0x46, 0xa0, 0xf1, 0xd4, 0x1b, 0x3b, 0x49, 0x95, 0x7f, 0xf7, 0x24, 0xfd, 0x4d,
	0x81, 0x45, 0x56, 0xf0, 0xff, 0x76, 0xb2, 0x5d, 0x3d, 0x12, 0xea, 0xbf, 0x64, 0xdd, 0x14, 0x7b,
	0xa7, 0x45, 0xeb, 0x56, 0x72, 0xef, 0xc8, 0xde, 0x38, 0x49, 0xfc, 0xcc, 0x8f, 0x61, 0x69, 0xd3,
	0x7b, 0x6e, 0xbb, 0x3d, 0x87, 0xdd, 0x69, 0xe9, 0x55, 0x4a, 0x58, 0x74, 0x31, 0x3e, 0xf4, 0xe8,
	0x2d, 0x93, 0x5d, 0x83, 0xa7, 0x3f, 0xda, 0xcc, 0xdf, 0x15, 0x50, 0xb1, 0x87, 0xf0, 0xfe, 0x0e,
	0x6d, 0x3b, 0x8e, 0xb8, 0x28, 0x2f, 0x5c, 0x64, 0x24, 0x5c, 0x94, 0xdf, 0x38, 0x23, 0x9c, 0x64,
	0x48, 0x4e, 0x52, 0xaa, 0x05, 0x31, 0x32, 0xee, 0x8f, 0xc9, 0xee, 0x13, 0x13, 0x5a, 0x62, 0xf1,
	0x36, 0xed, 0x42, 0xf8, 0xe2, 0xed, 0xd8, 0x90, 0x99, 0x54, 0x43, 0x1a, 0x1a, 0x00, 0xb5, 0xa3,
	0xe1, 0xe2, 0xbd, 0x67, 0xe6, 0xb7, 0x59, 0xd0, 0x1e, 0x61, 0xaf, 0x3b, 0x16, 0xfa, 0x6b, 0x46,
	0x59, 0x3a, 0x53, 0xae, 0x49, 0xed, 0x92, 0x92, 0xd2, 0x2e, 0x65, 0x12, 0xed, 0x12, 0xc7, 0xaf,
	0x27, 0xda, 0xab, 0xeb, 0x02, 0xbf, 0x91, 0x38, 0xb3, 0x6e, 0x08, 0xfc, 0x26, 0x35, 0x89, 0xe3,
	0x37, 0x05, 0x7e, 0x8b, 0xb6, 0x52, 0x1c, 0xbf, 0x25, 0xf0, 0xdb, 0xb4, 0x6d, 0xe2, 0xf8, 0x6d,
	0x81, 0xaf, 0xd1, 0xfe, 0x88, 0xe3, 0x6b, 0x02, 0xbf, 0x43, 0x1b, 0x21, 0x8e, 0xdf, 0x91, 0xe2,
	0x08, 0x12, 0x2e, 0xa7, 0xba, 0x2a, 0xe1, 0x72, 0x5d, 0xd5, 0xe4, 0x33, 0x57, 0xe0, 0x2d, 0xda,
	0xf7, 0x64, 0x27, 0x84, 0x6a, 0x5e, 0xc2, 0xa5, 0x50, 0x95, 0xd2, 0x73, 0xee, 0xfb, 0x0c, 0xcc,
	0x6d, 0x7a, 0x21, 0xea, 0xa2, 0x41, 0x90, 0x9a, 0x70, 0xc9, 0x3d, 0x99, 0x9d, 0x78, 0x00, 0x28,
	0xd5, 0xe2, 0x04, 0xa2, 0x24, 0x00, 0xb9, 0x94, 0x9c, 0x5a, 0x10, 0x44, 0x39, 0x7e, 0x8f, 0x06,
	0x40, 0x8f, 0xf0, 0x7b, 0x02, 0xbf, 0x4f, 0x03, 0x30, 0x1b, 0xe1, 0xf7, 0x05, 0xbe, 0x41, 0x03,
	0x30, 0x13, 0xe1, 0x1b, 0x02, 0xdf, 0xa4, 0x01, 0x28, 0x45, 0xf8, 0xa6, 0xc0, 0x1f, 0xd0, 0x00,
	0x94, 0x23, 0xfc, 0xc1, 0x54, 0x4d, 0xdd, 0x2e, 0x68, 0x4d, 0xec, 0x85, 0x76, 0xcf, 0x63, 0xed,
	0xd2, 0x74, 0x75, 0x2b, 0x7f, 0xa2, 0x32, 0xd9, 0x86, 0xb3, 0xd1, 0x53, 0xc3, 0x07, 0xbd, 0xf0,
	0x00, 0x0f, 0xc3, 0x53, 0x2d, 0x65, 0x5e, 0x83, 0x1c, 0x69, 0x7f, 0xc9, 0x51, 0xb0, 0xdf, 0x1b,
	0x04, 0x61, 0x34, 0x8d, 0x7d, 0xe8, 0x3a, 0xe4, 0x5c, 0x3b, 0x08, 0xa3, 0xb2, 0x4a, 0xff, 0x9b,
	0x1f, 0x81, 0xba, 0x7d, 0x80, 0x3d, 0xb4, 0x35, 0xec, 0xef, 0xa2, 0x01, 0x11, 0xa1, 0xdd, 0x39,
	0x9b, 0x47, 0xff, 0xeb, 0x15, 0x50, 0xf7, 0xf0, 0x90, 0x1c, 0x3a, 0x7b, 0xd8, 0xe1, 0xa7, 0x8b,
	0x0c, 0x11, 0x3a, 0x1e, 0x9d, 0xcf, 0x8a, 0x8e, 0x15, 0x7d, 0x99, 0x9f, 0x40, 0x31, 0xb2, 0x8a,
	0x1d, 0x01, 0x7a, 0x15, 0x34, 0xf6, 0x50, 0x20, 0x77, 0x9a, 0xbc, 0x4e, 0xaa, 0x6c, 0x88, 0xb5,
	0x91, 0xff, 0x8f, 0xfa, 0xfb, 0xcc, 0xc4, 0xfe, 0x9e, 0x35, 0xf6, 0xe6, 0xa1, 0x02, 0x67, 0xd7,
	0x7d, 0x1f, 0x79, 0x47, 0xea, 0x30, 0x7f, 0x1c, 0x50, 0xa6, 0x78, 0x1c, 0xb8, 0x02, 0x79, 0xf2,
	0xcb, 0xcb, 0x72, 0x9a, 0x30, 0x13, 0xd2, 0xb7, 0xa1, 0xe8, 0x13, 0x77, 0x75, 0x98, 0x85, 0x3c,
	0xa6, 0xf2, 0x9d, 0x5e, 0x72, 0x27, 0xbb, 0xf5, 0xe6, 0xc8, 0xa5, 0x91, 0xba, 0x92, 0xa9, 0xd2,
	0xfc, 0x58, 0x22, 0x30, 0xbf, 0x50, 0xe0, 0xc2, 0xfb, 0x5e, 0x30, 0xf4, 0x7d, 0x3c, 0x08, 0x91,
	0xc3, 0xcc, 0x39, 0x95, 0x25, 0xb7, 0x61, 0xc6, 0xa3, 0x6e, 0x8e, 0x9c, 0x26, 0xdf, 0x65, 0x13,
	0x61, 0xe0, 0xd3, 0x22, 0x71, 0xf3, 0x4b, 0x05, 0xe6, 0xb7, 0x30, 0xc9, 0x38, 0xb1, 0xee, 0x3b,
	0xa0, 0x46, 0x8f, 0x37, 0x04, 0xe6, 0xe7, 0xd9, 0x6b, 0x16, 0x27, 0x69, 0x44, 0xbc, 0xd2, 0x50,
	0x31, 0x96, 0x1a, 0x31, 0x20, 0xe8, 0x67, 0x53, 0xe8, 0xbf, 0x8e, 0xe9, 0x9b, 0x9f, 0xc3, 0x79,
	0x69, 0x0b, 0x6c, 0xb3, 0x67, 0x17, 0x1a, 0x57, 0xfd, 0x7f, 0xc9, 0x6d, 0x90, 0xbc, 0xba, 0xad,
	0x8b, 0x61, 0xb6, 0x1b, 0xb4, 0xe4, 0xf0, 0x74, 0xfb, 0xef, 0x29, 0x00, 0x61, 0x44, 0x56, 0x45,
	0x0e, 0x39, 0xc7, 0xa5, 0xed, 0xc3, 0xf4, 0x01, 0xdf, 0x45, 0x17, 0xe4, 0x5d, 0xc4, 0xc7, 0x28,
	0x44, 0xee, 0x64, 0x76, 0x97, 0x59, 0x9b, 0xb7, 0xc8, 0x5f, 0x73, 0x1b, 0x96, 0xa4, 0x04, 0x8d,
	0x8c, 0x12, 0x5e, 0xae, 0xf3, 0xdc, 0x1b, 0x7f, 0xd0, 0x88, 0xd9, 0x24, 0x33, 0x70, 0xd9, 0x84,
	0x5c, 0xdb, 0x1b, 0xf6, 0x75, 0x0d, 0xe6, 0x48, 0x4a, 0x75, 0xb0, 0x87, 0xca, 0x67, 0xc4, 0x57,
	0xf8, 0x02, 0x97, 0x95, 0xc6, 0x15, 0x28, 0xee, 0xe1, 0x7e, 0xac, 0xad, 0xa1, 0x45, 0x9e, 0xdd,
	0x1e, 0xe0, 0x10, 0x6f, 0x2b, 0x1f, 0xaa, 0x62, 0xc8, 0xdf, 0xdd, 0x9d, 0xa1, 0xaf, 0x4b, 0xd7,
	0xff, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x97, 0xb8, 0xe8, 0x46, 0x71, 0x15, 0x00, 0x00,
}
