// Code generated by protoc-gen-go. DO NOT EDIT.
// source: examples/documents/example.proto

package documentspb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import _ "github.com/centrifuge/precise-proofs/proofs/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Enum int32

const (
	Enum_type_one Enum = 0
	Enum_type_two Enum = 1
)

var Enum_name = map[int32]string{
	0: "type_one",
	1: "type_two",
}
var Enum_value = map[string]int32{
	"type_one": 0,
	"type_two": 1,
}

func (x Enum) String() string {
	return proto.EnumName(Enum_name, int32(x))
}
func (Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_example_1267a82a63a4d865, []int{0}
}

type ExampleDocument struct {
	ValueA               string   `protobuf:"bytes,1,opt,name=valueA,proto3" json:"valueA,omitempty"`
	ValueB               string   `protobuf:"bytes,2,opt,name=valueB,proto3" json:"valueB,omitempty"`
	Value1               int64    `protobuf:"varint,3,opt,name=value1,proto3" json:"value1,omitempty"`
	Value2               int64    `protobuf:"varint,4,opt,name=value2,proto3" json:"value2,omitempty"`
	ValueBytes1          []byte   `protobuf:"bytes,5,opt,name=value_bytes1,json=valueBytes1,proto3" json:"value_bytes1,omitempty"`
	ValueCamelCased      []byte   `protobuf:"bytes,6,opt,name=ValueCamelCased,proto3" json:"ValueCamelCased,omitempty"`
	ValueNotIgnored      []byte   `protobuf:"bytes,7,opt,name=value_not_ignored,json=valueNotIgnored,proto3" json:"value_not_ignored,omitempty"`
	ValueIgnored         []byte   `protobuf:"bytes,8,opt,name=value_ignored,json=valueIgnored,proto3" json:"value_ignored,omitempty"`
	ValueNotHashed       []byte   `protobuf:"bytes,9,opt,name=value_not_hashed,json=valueNotHashed,proto3" json:"value_not_hashed,omitempty"`
	EnumType             Enum     `protobuf:"varint,10,opt,name=enum_type,json=enumType,proto3,enum=documents.Enum" json:"enum_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExampleDocument) Reset()         { *m = ExampleDocument{} }
func (m *ExampleDocument) String() string { return proto.CompactTextString(m) }
func (*ExampleDocument) ProtoMessage()    {}
func (*ExampleDocument) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_1267a82a63a4d865, []int{0}
}
func (m *ExampleDocument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExampleDocument.Unmarshal(m, b)
}
func (m *ExampleDocument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExampleDocument.Marshal(b, m, deterministic)
}
func (dst *ExampleDocument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExampleDocument.Merge(dst, src)
}
func (m *ExampleDocument) XXX_Size() int {
	return xxx_messageInfo_ExampleDocument.Size(m)
}
func (m *ExampleDocument) XXX_DiscardUnknown() {
	xxx_messageInfo_ExampleDocument.DiscardUnknown(m)
}

var xxx_messageInfo_ExampleDocument proto.InternalMessageInfo

func (m *ExampleDocument) GetValueA() string {
	if m != nil {
		return m.ValueA
	}
	return ""
}

func (m *ExampleDocument) GetValueB() string {
	if m != nil {
		return m.ValueB
	}
	return ""
}

func (m *ExampleDocument) GetValue1() int64 {
	if m != nil {
		return m.Value1
	}
	return 0
}

func (m *ExampleDocument) GetValue2() int64 {
	if m != nil {
		return m.Value2
	}
	return 0
}

func (m *ExampleDocument) GetValueBytes1() []byte {
	if m != nil {
		return m.ValueBytes1
	}
	return nil
}

func (m *ExampleDocument) GetValueCamelCased() []byte {
	if m != nil {
		return m.ValueCamelCased
	}
	return nil
}

func (m *ExampleDocument) GetValueNotIgnored() []byte {
	if m != nil {
		return m.ValueNotIgnored
	}
	return nil
}

func (m *ExampleDocument) GetValueIgnored() []byte {
	if m != nil {
		return m.ValueIgnored
	}
	return nil
}

func (m *ExampleDocument) GetValueNotHashed() []byte {
	if m != nil {
		return m.ValueNotHashed
	}
	return nil
}

func (m *ExampleDocument) GetEnumType() Enum {
	if m != nil {
		return m.EnumType
	}
	return Enum_type_one
}

type AllFieldTypes struct {
	StringValue          string               `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3" json:"string_value,omitempty"`
	TimeStampValue       *timestamp.Timestamp `protobuf:"bytes,2,opt,name=time_stamp_value,json=timeStampValue,proto3" json:"time_stamp_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AllFieldTypes) Reset()         { *m = AllFieldTypes{} }
func (m *AllFieldTypes) String() string { return proto.CompactTextString(m) }
func (*AllFieldTypes) ProtoMessage()    {}
func (*AllFieldTypes) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_1267a82a63a4d865, []int{1}
}
func (m *AllFieldTypes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllFieldTypes.Unmarshal(m, b)
}
func (m *AllFieldTypes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllFieldTypes.Marshal(b, m, deterministic)
}
func (dst *AllFieldTypes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllFieldTypes.Merge(dst, src)
}
func (m *AllFieldTypes) XXX_Size() int {
	return xxx_messageInfo_AllFieldTypes.Size(m)
}
func (m *AllFieldTypes) XXX_DiscardUnknown() {
	xxx_messageInfo_AllFieldTypes.DiscardUnknown(m)
}

var xxx_messageInfo_AllFieldTypes proto.InternalMessageInfo

func (m *AllFieldTypes) GetStringValue() string {
	if m != nil {
		return m.StringValue
	}
	return ""
}

func (m *AllFieldTypes) GetTimeStampValue() *timestamp.Timestamp {
	if m != nil {
		return m.TimeStampValue
	}
	return nil
}

type AllFieldTypesSalts struct {
	StringValue          []byte   `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3" json:"string_value,omitempty"`
	TimeStampValue       []byte   `protobuf:"bytes,2,opt,name=time_stamp_value,json=timeStampValue,proto3" json:"time_stamp_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllFieldTypesSalts) Reset()         { *m = AllFieldTypesSalts{} }
func (m *AllFieldTypesSalts) String() string { return proto.CompactTextString(m) }
func (*AllFieldTypesSalts) ProtoMessage()    {}
func (*AllFieldTypesSalts) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_1267a82a63a4d865, []int{2}
}
func (m *AllFieldTypesSalts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllFieldTypesSalts.Unmarshal(m, b)
}
func (m *AllFieldTypesSalts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllFieldTypesSalts.Marshal(b, m, deterministic)
}
func (dst *AllFieldTypesSalts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllFieldTypesSalts.Merge(dst, src)
}
func (m *AllFieldTypesSalts) XXX_Size() int {
	return xxx_messageInfo_AllFieldTypesSalts.Size(m)
}
func (m *AllFieldTypesSalts) XXX_DiscardUnknown() {
	xxx_messageInfo_AllFieldTypesSalts.DiscardUnknown(m)
}

var xxx_messageInfo_AllFieldTypesSalts proto.InternalMessageInfo

func (m *AllFieldTypesSalts) GetStringValue() []byte {
	if m != nil {
		return m.StringValue
	}
	return nil
}

func (m *AllFieldTypesSalts) GetTimeStampValue() []byte {
	if m != nil {
		return m.TimeStampValue
	}
	return nil
}

type SimpleItem struct {
	ValueA               string   `protobuf:"bytes,1,opt,name=valueA,proto3" json:"valueA,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleItem) Reset()         { *m = SimpleItem{} }
func (m *SimpleItem) String() string { return proto.CompactTextString(m) }
func (*SimpleItem) ProtoMessage()    {}
func (*SimpleItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_1267a82a63a4d865, []int{3}
}
func (m *SimpleItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleItem.Unmarshal(m, b)
}
func (m *SimpleItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleItem.Marshal(b, m, deterministic)
}
func (dst *SimpleItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleItem.Merge(dst, src)
}
func (m *SimpleItem) XXX_Size() int {
	return xxx_messageInfo_SimpleItem.Size(m)
}
func (m *SimpleItem) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleItem.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleItem proto.InternalMessageInfo

func (m *SimpleItem) GetValueA() string {
	if m != nil {
		return m.ValueA
	}
	return ""
}

type RepeatedItem struct {
	ValueA               []*SimpleItem `protobuf:"bytes,1,rep,name=valueA,proto3" json:"valueA,omitempty"`
	ValueB               string        `protobuf:"bytes,2,opt,name=valueB,proto3" json:"valueB,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RepeatedItem) Reset()         { *m = RepeatedItem{} }
func (m *RepeatedItem) String() string { return proto.CompactTextString(m) }
func (*RepeatedItem) ProtoMessage()    {}
func (*RepeatedItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_1267a82a63a4d865, []int{4}
}
func (m *RepeatedItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepeatedItem.Unmarshal(m, b)
}
func (m *RepeatedItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepeatedItem.Marshal(b, m, deterministic)
}
func (dst *RepeatedItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepeatedItem.Merge(dst, src)
}
func (m *RepeatedItem) XXX_Size() int {
	return xxx_messageInfo_RepeatedItem.Size(m)
}
func (m *RepeatedItem) XXX_DiscardUnknown() {
	xxx_messageInfo_RepeatedItem.DiscardUnknown(m)
}

var xxx_messageInfo_RepeatedItem proto.InternalMessageInfo

func (m *RepeatedItem) GetValueA() []*SimpleItem {
	if m != nil {
		return m.ValueA
	}
	return nil
}

func (m *RepeatedItem) GetValueB() string {
	if m != nil {
		return m.ValueB
	}
	return ""
}

type SimpleMap struct {
	Value                map[int32]string `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SimpleMap) Reset()         { *m = SimpleMap{} }
func (m *SimpleMap) String() string { return proto.CompactTextString(m) }
func (*SimpleMap) ProtoMessage()    {}
func (*SimpleMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_1267a82a63a4d865, []int{5}
}
func (m *SimpleMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleMap.Unmarshal(m, b)
}
func (m *SimpleMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleMap.Marshal(b, m, deterministic)
}
func (dst *SimpleMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleMap.Merge(dst, src)
}
func (m *SimpleMap) XXX_Size() int {
	return xxx_messageInfo_SimpleMap.Size(m)
}
func (m *SimpleMap) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleMap.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleMap proto.InternalMessageInfo

func (m *SimpleMap) GetValue() map[int32]string {
	if m != nil {
		return m.Value
	}
	return nil
}

type SimpleStringMap struct {
	Value                map[string]string `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SimpleStringMap) Reset()         { *m = SimpleStringMap{} }
func (m *SimpleStringMap) String() string { return proto.CompactTextString(m) }
func (*SimpleStringMap) ProtoMessage()    {}
func (*SimpleStringMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_1267a82a63a4d865, []int{6}
}
func (m *SimpleStringMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleStringMap.Unmarshal(m, b)
}
func (m *SimpleStringMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleStringMap.Marshal(b, m, deterministic)
}
func (dst *SimpleStringMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleStringMap.Merge(dst, src)
}
func (m *SimpleStringMap) XXX_Size() int {
	return xxx_messageInfo_SimpleStringMap.Size(m)
}
func (m *SimpleStringMap) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleStringMap.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleStringMap proto.InternalMessageInfo

func (m *SimpleStringMap) GetValue() map[string]string {
	if m != nil {
		return m.Value
	}
	return nil
}

type NestedMap struct {
	Value                map[int32]*SimpleMap `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *NestedMap) Reset()         { *m = NestedMap{} }
func (m *NestedMap) String() string { return proto.CompactTextString(m) }
func (*NestedMap) ProtoMessage()    {}
func (*NestedMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_1267a82a63a4d865, []int{7}
}
func (m *NestedMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NestedMap.Unmarshal(m, b)
}
func (m *NestedMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NestedMap.Marshal(b, m, deterministic)
}
func (dst *NestedMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NestedMap.Merge(dst, src)
}
func (m *NestedMap) XXX_Size() int {
	return xxx_messageInfo_NestedMap.Size(m)
}
func (m *NestedMap) XXX_DiscardUnknown() {
	xxx_messageInfo_NestedMap.DiscardUnknown(m)
}

var xxx_messageInfo_NestedMap proto.InternalMessageInfo

func (m *NestedMap) GetValue() map[int32]*SimpleMap {
	if m != nil {
		return m.Value
	}
	return nil
}

type SimpleEntry struct {
	EntryKey             string   `protobuf:"bytes,1,opt,name=entry_key,json=entryKey,proto3" json:"entry_key,omitempty"`
	EntryValue           string   `protobuf:"bytes,2,opt,name=entry_value,json=entryValue,proto3" json:"entry_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleEntry) Reset()         { *m = SimpleEntry{} }
func (m *SimpleEntry) String() string { return proto.CompactTextString(m) }
func (*SimpleEntry) ProtoMessage()    {}
func (*SimpleEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_1267a82a63a4d865, []int{8}
}
func (m *SimpleEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleEntry.Unmarshal(m, b)
}
func (m *SimpleEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleEntry.Marshal(b, m, deterministic)
}
func (dst *SimpleEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleEntry.Merge(dst, src)
}
func (m *SimpleEntry) XXX_Size() int {
	return xxx_messageInfo_SimpleEntry.Size(m)
}
func (m *SimpleEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleEntry.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleEntry proto.InternalMessageInfo

func (m *SimpleEntry) GetEntryKey() string {
	if m != nil {
		return m.EntryKey
	}
	return ""
}

func (m *SimpleEntry) GetEntryValue() string {
	if m != nil {
		return m.EntryValue
	}
	return ""
}

type SimpleEntries struct {
	Entries              []*SimpleEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SimpleEntries) Reset()         { *m = SimpleEntries{} }
func (m *SimpleEntries) String() string { return proto.CompactTextString(m) }
func (*SimpleEntries) ProtoMessage()    {}
func (*SimpleEntries) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_1267a82a63a4d865, []int{9}
}
func (m *SimpleEntries) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleEntries.Unmarshal(m, b)
}
func (m *SimpleEntries) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleEntries.Marshal(b, m, deterministic)
}
func (dst *SimpleEntries) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleEntries.Merge(dst, src)
}
func (m *SimpleEntries) XXX_Size() int {
	return xxx_messageInfo_SimpleEntries.Size(m)
}
func (m *SimpleEntries) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleEntries.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleEntries proto.InternalMessageInfo

func (m *SimpleEntries) GetEntries() []*SimpleEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type Entry struct {
	EntryKey             string   `protobuf:"bytes,1,opt,name=entry_key,json=entryKey,proto3" json:"entry_key,omitempty"`
	ValueA               string   `protobuf:"bytes,2,opt,name=valueA,proto3" json:"valueA,omitempty"`
	ValueB               []byte   `protobuf:"bytes,3,opt,name=valueB,proto3" json:"valueB,omitempty"`
	ValueC               int64    `protobuf:"varint,4,opt,name=valueC,proto3" json:"valueC,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_1267a82a63a4d865, []int{10}
}
func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (dst *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(dst, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetEntryKey() string {
	if m != nil {
		return m.EntryKey
	}
	return ""
}

func (m *Entry) GetValueA() string {
	if m != nil {
		return m.ValueA
	}
	return ""
}

func (m *Entry) GetValueB() []byte {
	if m != nil {
		return m.ValueB
	}
	return nil
}

func (m *Entry) GetValueC() int64 {
	if m != nil {
		return m.ValueC
	}
	return 0
}

type Entries struct {
	Entries              []*Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entries) Reset()         { *m = Entries{} }
func (m *Entries) String() string { return proto.CompactTextString(m) }
func (*Entries) ProtoMessage()    {}
func (*Entries) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_1267a82a63a4d865, []int{11}
}
func (m *Entries) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entries.Unmarshal(m, b)
}
func (m *Entries) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entries.Marshal(b, m, deterministic)
}
func (dst *Entries) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entries.Merge(dst, src)
}
func (m *Entries) XXX_Size() int {
	return xxx_messageInfo_Entries.Size(m)
}
func (m *Entries) XXX_DiscardUnknown() {
	xxx_messageInfo_Entries.DiscardUnknown(m)
}

var xxx_messageInfo_Entries proto.InternalMessageInfo

func (m *Entries) GetEntries() []*Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type BytesKeyEntry struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BytesKeyEntry) Reset()         { *m = BytesKeyEntry{} }
func (m *BytesKeyEntry) String() string { return proto.CompactTextString(m) }
func (*BytesKeyEntry) ProtoMessage()    {}
func (*BytesKeyEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_1267a82a63a4d865, []int{12}
}
func (m *BytesKeyEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BytesKeyEntry.Unmarshal(m, b)
}
func (m *BytesKeyEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BytesKeyEntry.Marshal(b, m, deterministic)
}
func (dst *BytesKeyEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BytesKeyEntry.Merge(dst, src)
}
func (m *BytesKeyEntry) XXX_Size() int {
	return xxx_messageInfo_BytesKeyEntry.Size(m)
}
func (m *BytesKeyEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_BytesKeyEntry.DiscardUnknown(m)
}

var xxx_messageInfo_BytesKeyEntry proto.InternalMessageInfo

func (m *BytesKeyEntry) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *BytesKeyEntry) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type BytesKeyEntries struct {
	Entries              []*BytesKeyEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *BytesKeyEntries) Reset()         { *m = BytesKeyEntries{} }
func (m *BytesKeyEntries) String() string { return proto.CompactTextString(m) }
func (*BytesKeyEntries) ProtoMessage()    {}
func (*BytesKeyEntries) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_1267a82a63a4d865, []int{13}
}
func (m *BytesKeyEntries) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BytesKeyEntries.Unmarshal(m, b)
}
func (m *BytesKeyEntries) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BytesKeyEntries.Marshal(b, m, deterministic)
}
func (dst *BytesKeyEntries) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BytesKeyEntries.Merge(dst, src)
}
func (m *BytesKeyEntries) XXX_Size() int {
	return xxx_messageInfo_BytesKeyEntries.Size(m)
}
func (m *BytesKeyEntries) XXX_DiscardUnknown() {
	xxx_messageInfo_BytesKeyEntries.DiscardUnknown(m)
}

var xxx_messageInfo_BytesKeyEntries proto.InternalMessageInfo

func (m *BytesKeyEntries) GetEntries() []*BytesKeyEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type TwoLevelRepeatedDocument struct {
	ValueA               string          `protobuf:"bytes,1,opt,name=valueA,proto3" json:"valueA,omitempty"`
	ValueB               []*RepeatedItem `protobuf:"bytes,2,rep,name=valueB,proto3" json:"valueB,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *TwoLevelRepeatedDocument) Reset()         { *m = TwoLevelRepeatedDocument{} }
func (m *TwoLevelRepeatedDocument) String() string { return proto.CompactTextString(m) }
func (*TwoLevelRepeatedDocument) ProtoMessage()    {}
func (*TwoLevelRepeatedDocument) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_1267a82a63a4d865, []int{14}
}
func (m *TwoLevelRepeatedDocument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TwoLevelRepeatedDocument.Unmarshal(m, b)
}
func (m *TwoLevelRepeatedDocument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TwoLevelRepeatedDocument.Marshal(b, m, deterministic)
}
func (dst *TwoLevelRepeatedDocument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TwoLevelRepeatedDocument.Merge(dst, src)
}
func (m *TwoLevelRepeatedDocument) XXX_Size() int {
	return xxx_messageInfo_TwoLevelRepeatedDocument.Size(m)
}
func (m *TwoLevelRepeatedDocument) XXX_DiscardUnknown() {
	xxx_messageInfo_TwoLevelRepeatedDocument.DiscardUnknown(m)
}

var xxx_messageInfo_TwoLevelRepeatedDocument proto.InternalMessageInfo

func (m *TwoLevelRepeatedDocument) GetValueA() string {
	if m != nil {
		return m.ValueA
	}
	return ""
}

func (m *TwoLevelRepeatedDocument) GetValueB() []*RepeatedItem {
	if m != nil {
		return m.ValueB
	}
	return nil
}

type SimpleRepeatedDocument struct {
	ValueA               string   `protobuf:"bytes,1,opt,name=valueA,proto3" json:"valueA,omitempty"`
	ValueB               string   `protobuf:"bytes,2,opt,name=valueB,proto3" json:"valueB,omitempty"`
	ValueC               []string `protobuf:"bytes,3,rep,name=valueC,proto3" json:"valueC,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleRepeatedDocument) Reset()         { *m = SimpleRepeatedDocument{} }
func (m *SimpleRepeatedDocument) String() string { return proto.CompactTextString(m) }
func (*SimpleRepeatedDocument) ProtoMessage()    {}
func (*SimpleRepeatedDocument) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_1267a82a63a4d865, []int{15}
}
func (m *SimpleRepeatedDocument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleRepeatedDocument.Unmarshal(m, b)
}
func (m *SimpleRepeatedDocument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleRepeatedDocument.Marshal(b, m, deterministic)
}
func (dst *SimpleRepeatedDocument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleRepeatedDocument.Merge(dst, src)
}
func (m *SimpleRepeatedDocument) XXX_Size() int {
	return xxx_messageInfo_SimpleRepeatedDocument.Size(m)
}
func (m *SimpleRepeatedDocument) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleRepeatedDocument.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleRepeatedDocument proto.InternalMessageInfo

func (m *SimpleRepeatedDocument) GetValueA() string {
	if m != nil {
		return m.ValueA
	}
	return ""
}

func (m *SimpleRepeatedDocument) GetValueB() string {
	if m != nil {
		return m.ValueB
	}
	return ""
}

func (m *SimpleRepeatedDocument) GetValueC() []string {
	if m != nil {
		return m.ValueC
	}
	return nil
}

type SimpleMapDocument struct {
	ValueA               string            `protobuf:"bytes,1,opt,name=valueA,proto3" json:"valueA,omitempty"`
	ValueB               string            `protobuf:"bytes,2,opt,name=valueB,proto3" json:"valueB,omitempty"`
	ValueC               map[string]string `protobuf:"bytes,3,rep,name=valueC,proto3" json:"valueC,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ValueD               map[int32]string  `protobuf:"bytes,4,rep,name=valueD,proto3" json:"valueD,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SimpleMapDocument) Reset()         { *m = SimpleMapDocument{} }
func (m *SimpleMapDocument) String() string { return proto.CompactTextString(m) }
func (*SimpleMapDocument) ProtoMessage()    {}
func (*SimpleMapDocument) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_1267a82a63a4d865, []int{16}
}
func (m *SimpleMapDocument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleMapDocument.Unmarshal(m, b)
}
func (m *SimpleMapDocument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleMapDocument.Marshal(b, m, deterministic)
}
func (dst *SimpleMapDocument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleMapDocument.Merge(dst, src)
}
func (m *SimpleMapDocument) XXX_Size() int {
	return xxx_messageInfo_SimpleMapDocument.Size(m)
}
func (m *SimpleMapDocument) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleMapDocument.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleMapDocument proto.InternalMessageInfo

func (m *SimpleMapDocument) GetValueA() string {
	if m != nil {
		return m.ValueA
	}
	return ""
}

func (m *SimpleMapDocument) GetValueB() string {
	if m != nil {
		return m.ValueB
	}
	return ""
}

func (m *SimpleMapDocument) GetValueC() map[string]string {
	if m != nil {
		return m.ValueC
	}
	return nil
}

func (m *SimpleMapDocument) GetValueD() map[int32]string {
	if m != nil {
		return m.ValueD
	}
	return nil
}

type TwoLevelItem struct {
	ValueA               *SimpleItem `protobuf:"bytes,1,opt,name=valueA,proto3" json:"valueA,omitempty"`
	ValueB               string      `protobuf:"bytes,2,opt,name=valueB,proto3" json:"valueB,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TwoLevelItem) Reset()         { *m = TwoLevelItem{} }
func (m *TwoLevelItem) String() string { return proto.CompactTextString(m) }
func (*TwoLevelItem) ProtoMessage()    {}
func (*TwoLevelItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_1267a82a63a4d865, []int{17}
}
func (m *TwoLevelItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TwoLevelItem.Unmarshal(m, b)
}
func (m *TwoLevelItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TwoLevelItem.Marshal(b, m, deterministic)
}
func (dst *TwoLevelItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TwoLevelItem.Merge(dst, src)
}
func (m *TwoLevelItem) XXX_Size() int {
	return xxx_messageInfo_TwoLevelItem.Size(m)
}
func (m *TwoLevelItem) XXX_DiscardUnknown() {
	xxx_messageInfo_TwoLevelItem.DiscardUnknown(m)
}

var xxx_messageInfo_TwoLevelItem proto.InternalMessageInfo

func (m *TwoLevelItem) GetValueA() *SimpleItem {
	if m != nil {
		return m.ValueA
	}
	return nil
}

func (m *TwoLevelItem) GetValueB() string {
	if m != nil {
		return m.ValueB
	}
	return ""
}

type NestedRepeatedDocument struct {
	ValueA               string        `protobuf:"bytes,1,opt,name=valueA,proto3" json:"valueA,omitempty"`
	ValueB               string        `protobuf:"bytes,2,opt,name=valueB,proto3" json:"valueB,omitempty"`
	ValueC               []*SimpleItem `protobuf:"bytes,3,rep,name=valueC,proto3" json:"valueC,omitempty"`
	ValueD               *TwoLevelItem `protobuf:"bytes,4,opt,name=valueD,proto3" json:"valueD,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *NestedRepeatedDocument) Reset()         { *m = NestedRepeatedDocument{} }
func (m *NestedRepeatedDocument) String() string { return proto.CompactTextString(m) }
func (*NestedRepeatedDocument) ProtoMessage()    {}
func (*NestedRepeatedDocument) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_1267a82a63a4d865, []int{18}
}
func (m *NestedRepeatedDocument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NestedRepeatedDocument.Unmarshal(m, b)
}
func (m *NestedRepeatedDocument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NestedRepeatedDocument.Marshal(b, m, deterministic)
}
func (dst *NestedRepeatedDocument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NestedRepeatedDocument.Merge(dst, src)
}
func (m *NestedRepeatedDocument) XXX_Size() int {
	return xxx_messageInfo_NestedRepeatedDocument.Size(m)
}
func (m *NestedRepeatedDocument) XXX_DiscardUnknown() {
	xxx_messageInfo_NestedRepeatedDocument.DiscardUnknown(m)
}

var xxx_messageInfo_NestedRepeatedDocument proto.InternalMessageInfo

func (m *NestedRepeatedDocument) GetValueA() string {
	if m != nil {
		return m.ValueA
	}
	return ""
}

func (m *NestedRepeatedDocument) GetValueB() string {
	if m != nil {
		return m.ValueB
	}
	return ""
}

func (m *NestedRepeatedDocument) GetValueC() []*SimpleItem {
	if m != nil {
		return m.ValueC
	}
	return nil
}

func (m *NestedRepeatedDocument) GetValueD() *TwoLevelItem {
	if m != nil {
		return m.ValueD
	}
	return nil
}

type InvalidHashedFieldDocument struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvalidHashedFieldDocument) Reset()         { *m = InvalidHashedFieldDocument{} }
func (m *InvalidHashedFieldDocument) String() string { return proto.CompactTextString(m) }
func (*InvalidHashedFieldDocument) ProtoMessage()    {}
func (*InvalidHashedFieldDocument) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_1267a82a63a4d865, []int{19}
}
func (m *InvalidHashedFieldDocument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvalidHashedFieldDocument.Unmarshal(m, b)
}
func (m *InvalidHashedFieldDocument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvalidHashedFieldDocument.Marshal(b, m, deterministic)
}
func (dst *InvalidHashedFieldDocument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvalidHashedFieldDocument.Merge(dst, src)
}
func (m *InvalidHashedFieldDocument) XXX_Size() int {
	return xxx_messageInfo_InvalidHashedFieldDocument.Size(m)
}
func (m *InvalidHashedFieldDocument) XXX_DiscardUnknown() {
	xxx_messageInfo_InvalidHashedFieldDocument.DiscardUnknown(m)
}

var xxx_messageInfo_InvalidHashedFieldDocument proto.InternalMessageInfo

func (m *InvalidHashedFieldDocument) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type OneofSample struct {
	ValueA int32 `protobuf:"varint,1,opt,name=valueA,proto3" json:"valueA,omitempty"`
	// Types that are valid to be assigned to OneofBlock:
	//	*OneofSample_ValueB
	//	*OneofSample_ValueC
	OneofBlock           isOneofSample_OneofBlock `protobuf_oneof:"oneofBlock"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *OneofSample) Reset()         { *m = OneofSample{} }
func (m *OneofSample) String() string { return proto.CompactTextString(m) }
func (*OneofSample) ProtoMessage()    {}
func (*OneofSample) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_1267a82a63a4d865, []int{20}
}
func (m *OneofSample) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OneofSample.Unmarshal(m, b)
}
func (m *OneofSample) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OneofSample.Marshal(b, m, deterministic)
}
func (dst *OneofSample) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OneofSample.Merge(dst, src)
}
func (m *OneofSample) XXX_Size() int {
	return xxx_messageInfo_OneofSample.Size(m)
}
func (m *OneofSample) XXX_DiscardUnknown() {
	xxx_messageInfo_OneofSample.DiscardUnknown(m)
}

var xxx_messageInfo_OneofSample proto.InternalMessageInfo

func (m *OneofSample) GetValueA() int32 {
	if m != nil {
		return m.ValueA
	}
	return 0
}

type isOneofSample_OneofBlock interface {
	isOneofSample_OneofBlock()
}

type OneofSample_ValueB struct {
	ValueB int32 `protobuf:"varint,2,opt,name=valueB,proto3,oneof"`
}

type OneofSample_ValueC struct {
	ValueC string `protobuf:"bytes,3,opt,name=valueC,proto3,oneof"`
}

func (*OneofSample_ValueB) isOneofSample_OneofBlock() {}

func (*OneofSample_ValueC) isOneofSample_OneofBlock() {}

func (m *OneofSample) GetOneofBlock() isOneofSample_OneofBlock {
	if m != nil {
		return m.OneofBlock
	}
	return nil
}

func (m *OneofSample) GetValueB() int32 {
	if x, ok := m.GetOneofBlock().(*OneofSample_ValueB); ok {
		return x.ValueB
	}
	return 0
}

func (m *OneofSample) GetValueC() string {
	if x, ok := m.GetOneofBlock().(*OneofSample_ValueC); ok {
		return x.ValueC
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*OneofSample) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _OneofSample_OneofMarshaler, _OneofSample_OneofUnmarshaler, _OneofSample_OneofSizer, []interface{}{
		(*OneofSample_ValueB)(nil),
		(*OneofSample_ValueC)(nil),
	}
}

func _OneofSample_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*OneofSample)
	// oneofBlock
	switch x := m.OneofBlock.(type) {
	case *OneofSample_ValueB:
		b.EncodeVarint(2<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.ValueB))
	case *OneofSample_ValueC:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.ValueC)
	case nil:
	default:
		return fmt.Errorf("OneofSample.OneofBlock has unexpected type %T", x)
	}
	return nil
}

func _OneofSample_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*OneofSample)
	switch tag {
	case 2: // oneofBlock.valueB
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.OneofBlock = &OneofSample_ValueB{int32(x)}
		return true, err
	case 3: // oneofBlock.valueC
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.OneofBlock = &OneofSample_ValueC{x}
		return true, err
	default:
		return false, nil
	}
}

func _OneofSample_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*OneofSample)
	// oneofBlock
	switch x := m.OneofBlock.(type) {
	case *OneofSample_ValueB:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.ValueB))
	case *OneofSample_ValueC:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.ValueC)))
		n += len(x.ValueC)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type LongDocument struct {
	Value0               int64    `protobuf:"varint,16,opt,name=value0,proto3" json:"value0,omitempty"`
	Value1               int64    `protobuf:"varint,1,opt,name=value1,proto3" json:"value1,omitempty"`
	Value2               int64    `protobuf:"varint,2,opt,name=value2,proto3" json:"value2,omitempty"`
	Value3               int64    `protobuf:"varint,3,opt,name=value3,proto3" json:"value3,omitempty"`
	Value4               int64    `protobuf:"varint,4,opt,name=value4,proto3" json:"value4,omitempty"`
	Value5               int64    `protobuf:"varint,5,opt,name=value5,proto3" json:"value5,omitempty"`
	Value6               int64    `protobuf:"varint,6,opt,name=value6,proto3" json:"value6,omitempty"`
	Value7               int64    `protobuf:"varint,7,opt,name=value7,proto3" json:"value7,omitempty"`
	Value8               int64    `protobuf:"varint,8,opt,name=value8,proto3" json:"value8,omitempty"`
	Value9               int64    `protobuf:"varint,9,opt,name=value9,proto3" json:"value9,omitempty"`
	ValueA               int64    `protobuf:"varint,10,opt,name=valueA,proto3" json:"valueA,omitempty"`
	ValueB               int64    `protobuf:"varint,11,opt,name=valueB,proto3" json:"valueB,omitempty"`
	ValueC               int64    `protobuf:"varint,12,opt,name=valueC,proto3" json:"valueC,omitempty"`
	ValueD               int64    `protobuf:"varint,13,opt,name=valueD,proto3" json:"valueD,omitempty"`
	ValueE               int64    `protobuf:"varint,14,opt,name=valueE,proto3" json:"valueE,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LongDocument) Reset()         { *m = LongDocument{} }
func (m *LongDocument) String() string { return proto.CompactTextString(m) }
func (*LongDocument) ProtoMessage()    {}
func (*LongDocument) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_1267a82a63a4d865, []int{21}
}
func (m *LongDocument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LongDocument.Unmarshal(m, b)
}
func (m *LongDocument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LongDocument.Marshal(b, m, deterministic)
}
func (dst *LongDocument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LongDocument.Merge(dst, src)
}
func (m *LongDocument) XXX_Size() int {
	return xxx_messageInfo_LongDocument.Size(m)
}
func (m *LongDocument) XXX_DiscardUnknown() {
	xxx_messageInfo_LongDocument.DiscardUnknown(m)
}

var xxx_messageInfo_LongDocument proto.InternalMessageInfo

func (m *LongDocument) GetValue0() int64 {
	if m != nil {
		return m.Value0
	}
	return 0
}

func (m *LongDocument) GetValue1() int64 {
	if m != nil {
		return m.Value1
	}
	return 0
}

func (m *LongDocument) GetValue2() int64 {
	if m != nil {
		return m.Value2
	}
	return 0
}

func (m *LongDocument) GetValue3() int64 {
	if m != nil {
		return m.Value3
	}
	return 0
}

func (m *LongDocument) GetValue4() int64 {
	if m != nil {
		return m.Value4
	}
	return 0
}

func (m *LongDocument) GetValue5() int64 {
	if m != nil {
		return m.Value5
	}
	return 0
}

func (m *LongDocument) GetValue6() int64 {
	if m != nil {
		return m.Value6
	}
	return 0
}

func (m *LongDocument) GetValue7() int64 {
	if m != nil {
		return m.Value7
	}
	return 0
}

func (m *LongDocument) GetValue8() int64 {
	if m != nil {
		return m.Value8
	}
	return 0
}

func (m *LongDocument) GetValue9() int64 {
	if m != nil {
		return m.Value9
	}
	return 0
}

func (m *LongDocument) GetValueA() int64 {
	if m != nil {
		return m.ValueA
	}
	return 0
}

func (m *LongDocument) GetValueB() int64 {
	if m != nil {
		return m.ValueB
	}
	return 0
}

func (m *LongDocument) GetValueC() int64 {
	if m != nil {
		return m.ValueC
	}
	return 0
}

func (m *LongDocument) GetValueD() int64 {
	if m != nil {
		return m.ValueD
	}
	return 0
}

func (m *LongDocument) GetValueE() int64 {
	if m != nil {
		return m.ValueE
	}
	return 0
}

type Integers struct {
	ValueA               int32    `protobuf:"varint,1,opt,name=valueA,proto3" json:"valueA,omitempty"`
	ValueB               int64    `protobuf:"varint,2,opt,name=valueB,proto3" json:"valueB,omitempty"`
	ValueC               uint32   `protobuf:"varint,3,opt,name=valueC,proto3" json:"valueC,omitempty"`
	ValueD               uint64   `protobuf:"varint,4,opt,name=valueD,proto3" json:"valueD,omitempty"`
	ValueE               int32    `protobuf:"zigzag32,5,opt,name=valueE,proto3" json:"valueE,omitempty"`
	ValueF               int64    `protobuf:"zigzag64,6,opt,name=valueF,proto3" json:"valueF,omitempty"`
	ValueG               uint32   `protobuf:"fixed32,7,opt,name=valueG,proto3" json:"valueG,omitempty"`
	ValueH               uint64   `protobuf:"fixed64,8,opt,name=valueH,proto3" json:"valueH,omitempty"`
	ValueI               int32    `protobuf:"fixed32,9,opt,name=valueI,proto3" json:"valueI,omitempty"`
	ValueJ               int64    `protobuf:"fixed64,10,opt,name=valueJ,proto3" json:"valueJ,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Integers) Reset()         { *m = Integers{} }
func (m *Integers) String() string { return proto.CompactTextString(m) }
func (*Integers) ProtoMessage()    {}
func (*Integers) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_1267a82a63a4d865, []int{22}
}
func (m *Integers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Integers.Unmarshal(m, b)
}
func (m *Integers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Integers.Marshal(b, m, deterministic)
}
func (dst *Integers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Integers.Merge(dst, src)
}
func (m *Integers) XXX_Size() int {
	return xxx_messageInfo_Integers.Size(m)
}
func (m *Integers) XXX_DiscardUnknown() {
	xxx_messageInfo_Integers.DiscardUnknown(m)
}

var xxx_messageInfo_Integers proto.InternalMessageInfo

func (m *Integers) GetValueA() int32 {
	if m != nil {
		return m.ValueA
	}
	return 0
}

func (m *Integers) GetValueB() int64 {
	if m != nil {
		return m.ValueB
	}
	return 0
}

func (m *Integers) GetValueC() uint32 {
	if m != nil {
		return m.ValueC
	}
	return 0
}

func (m *Integers) GetValueD() uint64 {
	if m != nil {
		return m.ValueD
	}
	return 0
}

func (m *Integers) GetValueE() int32 {
	if m != nil {
		return m.ValueE
	}
	return 0
}

func (m *Integers) GetValueF() int64 {
	if m != nil {
		return m.ValueF
	}
	return 0
}

func (m *Integers) GetValueG() uint32 {
	if m != nil {
		return m.ValueG
	}
	return 0
}

func (m *Integers) GetValueH() uint64 {
	if m != nil {
		return m.ValueH
	}
	return 0
}

func (m *Integers) GetValueI() int32 {
	if m != nil {
		return m.ValueI
	}
	return 0
}

func (m *Integers) GetValueJ() int64 {
	if m != nil {
		return m.ValueJ
	}
	return 0
}

func init() {
	proto.RegisterType((*ExampleDocument)(nil), "documents.ExampleDocument")
	proto.RegisterType((*AllFieldTypes)(nil), "documents.AllFieldTypes")
	proto.RegisterType((*AllFieldTypesSalts)(nil), "documents.AllFieldTypesSalts")
	proto.RegisterType((*SimpleItem)(nil), "documents.SimpleItem")
	proto.RegisterType((*RepeatedItem)(nil), "documents.RepeatedItem")
	proto.RegisterType((*SimpleMap)(nil), "documents.SimpleMap")
	proto.RegisterMapType((map[int32]string)(nil), "documents.SimpleMap.ValueEntry")
	proto.RegisterType((*SimpleStringMap)(nil), "documents.SimpleStringMap")
	proto.RegisterMapType((map[string]string)(nil), "documents.SimpleStringMap.ValueEntry")
	proto.RegisterType((*NestedMap)(nil), "documents.NestedMap")
	proto.RegisterMapType((map[int32]*SimpleMap)(nil), "documents.NestedMap.ValueEntry")
	proto.RegisterType((*SimpleEntry)(nil), "documents.SimpleEntry")
	proto.RegisterType((*SimpleEntries)(nil), "documents.SimpleEntries")
	proto.RegisterType((*Entry)(nil), "documents.Entry")
	proto.RegisterType((*Entries)(nil), "documents.Entries")
	proto.RegisterType((*BytesKeyEntry)(nil), "documents.BytesKeyEntry")
	proto.RegisterType((*BytesKeyEntries)(nil), "documents.BytesKeyEntries")
	proto.RegisterType((*TwoLevelRepeatedDocument)(nil), "documents.TwoLevelRepeatedDocument")
	proto.RegisterType((*SimpleRepeatedDocument)(nil), "documents.SimpleRepeatedDocument")
	proto.RegisterType((*SimpleMapDocument)(nil), "documents.SimpleMapDocument")
	proto.RegisterMapType((map[string]string)(nil), "documents.SimpleMapDocument.ValueCEntry")
	proto.RegisterMapType((map[int32]string)(nil), "documents.SimpleMapDocument.ValueDEntry")
	proto.RegisterType((*TwoLevelItem)(nil), "documents.TwoLevelItem")
	proto.RegisterType((*NestedRepeatedDocument)(nil), "documents.NestedRepeatedDocument")
	proto.RegisterType((*InvalidHashedFieldDocument)(nil), "documents.InvalidHashedFieldDocument")
	proto.RegisterType((*OneofSample)(nil), "documents.oneofSample")
	proto.RegisterType((*LongDocument)(nil), "documents.LongDocument")
	proto.RegisterType((*Integers)(nil), "documents.Integers")
	proto.RegisterEnum("documents.Enum", Enum_name, Enum_value)
}

func init() {
	proto.RegisterFile("examples/documents/example.proto", fileDescriptor_example_1267a82a63a4d865)
}

var fileDescriptor_example_1267a82a63a4d865 = []byte{
	// 1176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x57, 0x41, 0x4f, 0xe3, 0xc6,
	0x17, 0xc7, 0x09, 0x01, 0xf2, 0xec, 0x90, 0xe0, 0x3f, 0x7f, 0x6a, 0x65, 0x0f, 0xa4, 0x56, 0x2b,
	0x59, 0x68, 0x49, 0x96, 0xb0, 0xec, 0x42, 0xa5, 0x6a, 0xbb, 0x4e, 0x02, 0x04, 0x76, 0xd1, 0xca,
	0xb0, 0xab, 0xaa, 0x97, 0xd4, 0xe0, 0x21, 0x1b, 0xe1, 0xd8, 0x56, 0xec, 0xb0, 0x44, 0xea, 0x77,
	0xa8, 0xd4, 0x4f, 0xd0, 0xe3, 0x1e, 0x7b, 0xee, 0x0d, 0xa9, 0x5f, 0x89, 0x1e, 0xaa, 0x1e, 0xaa,
	0x99, 0xf1, 0x8c, 0xc7, 0x24, 0x69, 0xd8, 0xed, 0x2d, 0xf3, 0x9b, 0x37, 0xbf, 0xf7, 0x7b, 0x6f,
	0xde, 0x3c, 0xbf, 0x40, 0x05, 0xdd, 0xd8, 0xfd, 0xc0, 0x45, 0x61, 0xcd, 0xf1, 0x2f, 0x86, 0x7d,
	0xe4, 0x45, 0x61, 0x2d, 0x86, 0xaa, 0xc1, 0xc0, 0x8f, 0x7c, 0x35, 0xcf, 0x37, 0xca, 0xeb, 0x5d,
	0xdf, 0xef, 0xba, 0xa8, 0x46, 0x36, 0xce, 0x87, 0x97, 0xb5, 0xa8, 0xd7, 0x47, 0x61, 0x64, 0xf7,
	0x03, 0x6a, 0x5b, 0xfe, 0xb6, 0xeb, 0x07, 0x57, 0xdd, 0x6a, 0xcf, 0xab, 0xd9, 0x2e, 0xba, 0x41,
	0x23, 0x0f, 0x0d, 0x6b, 0xc1, 0x00, 0x5d, 0xf4, 0x42, 0xb4, 0x19, 0x0c, 0x7c, 0xff, 0x32, 0xac,
	0x5e, 0x6f, 0xd7, 0xe8, 0x2f, 0xca, 0x42, 0x17, 0xf4, 0xb8, 0xfe, 0x77, 0x06, 0x8a, 0x2d, 0xea,
	0xbc, 0x19, 0x3b, 0x55, 0xd7, 0x60, 0xe1, 0xda, 0x76, 0x87, 0xe8, 0xa5, 0x26, 0x55, 0x24, 0x23,
	0x6f, 0xc5, 0x2b, 0x8e, 0x9b, 0x5a, 0x46, 0xc0, 0x4d, 0x8e, 0x6f, 0x69, 0xd9, 0x8a, 0x64, 0x64,
	0x63, 0x7c, 0x8b, 0xe3, 0x75, 0x6d, 0x5e, 0xc0, 0xeb, 0xea, 0x97, 0xa0, 0x90, 0x5f, 0x9d, 0xf3,
	0x51, 0x84, 0xc2, 0x2d, 0x2d, 0x57, 0x91, 0x0c, 0xc5, 0x92, 0x29, 0x1b, 0x81, 0x54, 0x03, 0x8a,
	0xef, 0xf0, 0xb2, 0x61, 0xf7, 0x91, 0xdb, 0xb0, 0x43, 0xe4, 0x68, 0x0b, 0xc4, 0xea, 0x3e, 0xac,
	0x6e, 0xc1, 0x0a, 0x25, 0xf3, 0xfc, 0xa8, 0xd3, 0xeb, 0x7a, 0xfe, 0x00, 0x39, 0xda, 0x22, 0xb6,
	0x35, 0x73, 0xbf, 0xde, 0xde, 0xc1, 0x9c, 0x55, 0x24, 0xfb, 0x27, 0x7e, 0xd4, 0xa6, 0xbb, 0xea,
	0x06, 0x14, 0xe8, 0x11, 0x66, 0xbe, 0x94, 0x98, 0x4b, 0x16, 0xd5, 0xc6, 0x6c, 0x6b, 0x50, 0x4a,
	0xe8, 0xdf, 0xdb, 0xe1, 0x7b, 0xe4, 0x68, 0x79, 0x6a, 0xfe, 0x91, 0x98, 0x2f, 0x33, 0xf6, 0x43,
	0xb2, 0xa9, 0x3e, 0x86, 0x3c, 0xf2, 0x86, 0xfd, 0x4e, 0x34, 0x0a, 0x90, 0x06, 0x15, 0xc9, 0x58,
	0xae, 0x17, 0xab, 0xfc, 0x3e, 0xab, 0x2d, 0x6f, 0xd8, 0xb7, 0x96, 0xb0, 0xc5, 0xd9, 0x28, 0x40,
	0xfa, 0x0d, 0x14, 0x5e, 0xba, 0xee, 0x7e, 0x0f, 0xb9, 0x0e, 0x5e, 0x87, 0x38, 0x37, 0x61, 0x34,
	0xe8, 0x79, 0xdd, 0x0e, 0xe1, 0x8d, 0x6f, 0x40, 0xa6, 0x18, 0x89, 0x5d, 0x6d, 0x42, 0x09, 0x17,
	0x41, 0x87, 0x54, 0x41, 0x6c, 0x86, 0x2f, 0x44, 0xae, 0x97, 0xab, 0xb4, 0x5a, 0xaa, 0xac, 0x5a,
	0xaa, 0x67, 0xac, 0x5a, 0xac, 0x65, 0x7c, 0xe6, 0x14, 0xff, 0x24, 0x2c, 0xba, 0x0d, 0x6a, 0xca,
	0xf3, 0xa9, 0xed, 0x46, 0x93, 0xdd, 0x2b, 0x69, 0xf7, 0xc6, 0x14, 0xf7, 0xca, 0x98, 0x8b, 0xaf,
	0x00, 0x4e, 0x7b, 0xb8, 0xb2, 0xda, 0x11, 0xea, 0x4f, 0xab, 0x2a, 0xfd, 0x2d, 0x28, 0x16, 0x0a,
	0x90, 0x1d, 0x21, 0x87, 0xd8, 0x6d, 0x0a, 0x76, 0x59, 0x43, 0xae, 0xff, 0x5f, 0xc8, 0x5e, 0x42,
	0x37, 0xab, 0x28, 0xf5, 0x9f, 0x20, 0x4f, 0xad, 0x5f, 0xdb, 0x81, 0xba, 0x03, 0x39, 0x16, 0x0f,
	0xa6, 0x5c, 0x1f, 0xa3, 0x7c, 0x6d, 0x07, 0x55, 0x22, 0xba, 0xe5, 0x45, 0x83, 0x91, 0x45, 0xad,
	0xcb, 0xbb, 0x00, 0x09, 0xa8, 0x96, 0x20, 0x7b, 0x85, 0x46, 0x44, 0x7d, 0xce, 0xc2, 0x3f, 0xd5,
	0x55, 0x46, 0x4b, 0x5d, 0xd3, 0xc5, 0x37, 0x99, 0x5d, 0x49, 0xff, 0x59, 0x82, 0x22, 0x65, 0x3e,
	0x25, 0xa9, 0xc3, 0x22, 0xcc, 0xb4, 0x88, 0xaf, 0xc7, 0x44, 0x70, 0x53, 0x41, 0x8a, 0x99, 0xfb,
	0xed, 0xf6, 0x0e, 0x2a, 0x33, 0x15, 0xe5, 0x67, 0x29, 0xfa, 0x45, 0x82, 0xfc, 0x09, 0x0a, 0x23,
	0xe4, 0xcc, 0x48, 0x08, 0x37, 0x9a, 0x90, 0x90, 0x93, 0x19, 0x09, 0xd9, 0x10, 0xdd, 0xcb, 0xf5,
	0xd5, 0x49, 0x79, 0x16, 0x45, 0x1d, 0x83, 0x4c, 0x71, 0x4a, 0xf8, 0x08, 0xbf, 0x9d, 0x68, 0x30,
	0xea, 0x24, 0x51, 0x2d, 0x11, 0xe0, 0x18, 0x8d, 0xd4, 0x75, 0x90, 0xe9, 0xa6, 0x18, 0x20, 0x10,
	0x88, 0x96, 0xdb, 0x3b, 0x28, 0x24, 0x64, 0x3d, 0x14, 0xaa, 0x2d, 0x58, 0x44, 0xf4, 0x67, 0x1c,
	0xe6, 0xda, 0x98, 0x1e, 0x9a, 0xe3, 0xff, 0x91, 0x1c, 0xff, 0x7e, 0x7b, 0x27, 0xf8, 0xb7, 0xd8,
	0x59, 0xdd, 0x85, 0xdc, 0x03, 0xe4, 0x25, 0xe5, 0x9d, 0x99, 0xd2, 0x34, 0xb3, 0xe4, 0x91, 0xdc,
	0x6f, 0x9a, 0x8d, 0x54, 0x73, 0x6c, 0xe8, 0x47, 0xb0, 0xc8, 0xf4, 0xbf, 0xb8, 0xaf, 0xbf, 0x94,
	0x6a, 0x24, 0xb3, 0x95, 0xbf, 0x80, 0x02, 0xe9, 0xa7, 0xc7, 0x68, 0x44, 0x23, 0xd0, 0x60, 0xd1,
	0x76, 0x9c, 0x01, 0x0a, 0xc3, 0xf8, 0x65, 0xb3, 0xe5, 0xe4, 0xc2, 0xd1, 0xbf, 0x87, 0xa2, 0x48,
	0x30, 0x31, 0xa9, 0x9a, 0x20, 0x2a, 0xe5, 0xcd, 0x5c, 0xc1, 0xe2, 0x56, 0xb1, 0x38, 0xe6, 0x26,
	0x91, 0x76, 0x01, 0xda, 0xd9, 0x07, 0xff, 0x15, 0xba, 0x46, 0x2e, 0x7b, 0xfd, 0x33, 0xbf, 0x3f,
	0x35, 0xe1, 0xa9, 0x63, 0xcf, 0x5f, 0x08, 0x9e, 0xc5, 0x16, 0xc2, 0x7b, 0xc0, 0x8f, 0xb0, 0x46,
	0xaf, 0xf9, 0xc1, 0x2e, 0x66, 0x7d, 0xe2, 0x1a, 0x5a, 0xb6, 0x92, 0xe5, 0x78, 0x43, 0xff, 0x23,
	0x03, 0x2b, 0xbc, 0xb2, 0x3f, 0x9b, 0xfd, 0x20, 0xc5, 0x2e, 0xd7, 0x8d, 0x49, 0xef, 0x86, 0xb1,
	0xd3, 0x67, 0xd9, 0x48, 0x75, 0x87, 0xf8, 0xb8, 0xfa, 0x5d, 0x4c, 0xd4, 0xd4, 0xe6, 0x1f, 0x4a,
	0xd4, 0xa4, 0x0f, 0x3c, 0x3e, 0x57, 0xde, 0x03, 0x59, 0xe0, 0xff, 0x94, 0x0e, 0xc3, 0x8f, 0x36,
	0x3f, 0xbd, 0x5d, 0xbe, 0x05, 0x85, 0x55, 0xc3, 0xd8, 0x37, 0x40, 0xfa, 0xfc, 0x6f, 0xc0, 0x47,
	0x09, 0xd6, 0x68, 0x3b, 0xfb, 0xcf, 0x05, 0xb0, 0x79, 0xef, 0x8a, 0xfe, 0x55, 0x51, 0x83, 0x97,
	0x6a, 0x93, 0xbc, 0xee, 0x74, 0xa9, 0x8a, 0x91, 0xb2, 0xbc, 0xeb, 0x7b, 0x50, 0x6e, 0x7b, 0xd7,
	0xb6, 0xdb, 0x73, 0xe8, 0x1c, 0x41, 0x3e, 0xcc, 0x5c, 0xed, 0xa3, 0xa4, 0x5d, 0x4b, 0x46, 0x9e,
	0x8d, 0x1e, 0xf1, 0x23, 0xed, 0x82, 0xec, 0x7b, 0xc8, 0xbf, 0x3c, 0x25, 0x53, 0xdc, 0xbd, 0xc8,
	0x72, 0x3c, 0x32, 0x2d, 0x15, 0x59, 0xee, 0x70, 0x8e, 0xc7, 0xa6, 0x09, 0xb1, 0x49, 0x46, 0x9e,
	0xef, 0x34, 0x4c, 0x05, 0x80, 0x50, 0x9b, 0xae, 0x7f, 0x71, 0xa5, 0xff, 0x99, 0x01, 0xe5, 0x95,
	0xef, 0x75, 0xc7, 0x92, 0xf8, 0x44, 0x2b, 0x09, 0x3d, 0xec, 0x89, 0x30, 0x10, 0x4a, 0x53, 0x06,
	0xc2, 0x4c, 0x6a, 0x20, 0x64, 0xf8, 0x76, 0x6a, 0x80, 0xdc, 0xe6, 0xf8, 0xd3, 0x54, 0x8f, 0x7c,
	0xca, 0xf1, 0x1d, 0x32, 0x3a, 0x32, 0x7c, 0x87, 0xe3, 0xcf, 0xc8, 0xb0, 0xc8, 0xf0, 0x67, 0x1c,
	0x7f, 0x4e, 0x06, 0x43, 0x86, 0x3f, 0xe7, 0xf8, 0x2e, 0x99, 0x00, 0x19, 0xbe, 0xcb, 0xf1, 0x3d,
	0x32, 0xea, 0x31, 0x7c, 0x4f, 0x48, 0x2d, 0x08, 0xb8, 0x58, 0x34, 0xb2, 0x80, 0x8b, 0x5d, 0x43,
	0x11, 0x7b, 0x3c, 0xc7, 0x9b, 0x5a, 0x41, 0xc0, 0x9b, 0x1c, 0x6f, 0x69, 0xcb, 0x02, 0xde, 0xd2,
	0xff, 0x92, 0x60, 0xa9, 0xed, 0x45, 0xa8, 0x8b, 0x06, 0xe1, 0xd4, 0xfb, 0x4d, 0x57, 0x6e, 0x76,
	0x62, 0xeb, 0x92, 0x8c, 0xc2, 0x04, 0x11, 0x38, 0xb9, 0xf3, 0x13, 0x44, 0xe0, 0xe4, 0xae, 0x30,
	0x11, 0x1c, 0xdf, 0x27, 0xc9, 0x55, 0x63, 0x7c, 0x9f, 0xe3, 0x07, 0x24, 0xb9, 0x8b, 0x31, 0x7e,
	0xc0, 0xf1, 0x43, 0x92, 0xdc, 0x85, 0x18, 0x3f, 0xe4, 0x78, 0x9b, 0x24, 0xb7, 0x18, 0xe3, 0x6d,
	0x8e, 0x1f, 0x91, 0xe4, 0x96, 0x62, 0xfc, 0x68, 0x43, 0x87, 0x79, 0x3c, 0x34, 0xab, 0x0a, 0x2c,
	0xe1, 0x99, 0xba, 0xe3, 0x7b, 0xa8, 0x34, 0xc7, 0x57, 0xd1, 0x07, 0xbf, 0x24, 0x99, 0x8f, 0xa1,
	0x70, 0xe1, 0xf7, 0x93, 0x37, 0x66, 0x2a, 0xf1, 0x7f, 0x9a, 0x37, 0x78, 0x10, 0x7e, 0x23, 0xfd,
	0x20, 0xf3, 0xad, 0xe0, 0xfc, 0x7c, 0x81, 0x8c, 0xc7, 0xdb, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff,
	0xf4, 0xbe, 0x9f, 0x64, 0x89, 0x0d, 0x00, 0x00,
}
